// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: abtest_common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.Protocol {

  /// <summary>Holder for reflection information generated from abtest_common.proto</summary>
  public static partial class AbtestCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for abtest_common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AbtestCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNhYnRlc3RfY29tbW9uLnByb3RvIo0BCgxBQlRlc3RGaWx0ZXISCwoDa2V5",
            "GAEgASgJEiEKCG9wZXJhdG9yGAIgASgOMg8uRmlsdGVyT3BlcmF0b3ISLgoK",
            "dmFsdWVfdHlwZRgDIAEoDjIaLkFCVGVzdEZpbHRlclZhbHVlVHlwZUVudW0S",
            "DQoFdmFsdWUYBCABKAkSDgoGdmFsdWVzGAUgAygJIjAKDkFCVGVzdEFsbE1h",
            "dGNoEh4KB2ZpbHRlcnMYASADKAsyDS5BQlRlc3RGaWx0ZXIicAoORXhwZXJp",
            "bWVudEl0ZW0SCgoCaWQYASABKAUSDgoGY29uZmlnGAIgASgJEh0KBHR5cGUY",
            "AyABKA4yDy5FeHBlcmltZW50VHlwZRISCgp3aGl0ZV9saXN0GAQgAygJEg8K",
            "B2FwcGxpZWQYBSABKAgiuQIKCkFCVGVzdEl0ZW0SCgoCaWQYASABKAkSCwoD",
            "YXBwGAIgASgJEgwKBG5hbWUYAyABKAkSDAoEZGVzYxgEIAEoCRISCgpmbG93",
            "X2xpbWl0GAUgASgNEhcKD2FidGVzdF9jb2RlbmFtZRgGIAEoCRIkCgthbnlf",
            "bWF0Y2hlcxgHIAMoCzIPLkFCVGVzdEFsbE1hdGNoEikKEGV4cGVyaW1lbnRf",
            "aXRlbXMYCCADKAsyDy5FeHBlcmltZW50SXRlbRIRCglsYXN0X2V0YWcYCSAB",
            "KAkSHQoGc3RhdHVzGAogASgOMg0uQUJUZXN0U3RhdHVzEh4KFndoaXRlbGlz",
            "dF9tYXRjaF9maWx0ZXIYCyABKAgSEgoKY3JlYXRlZF9hdBgMIAEoDRISCgp1",
            "cGRhdGVkX2F0GA0gASgNIiwKCkFCVGVzdERhdGESDQoFZ3JvdXAYASABKAkS",
            "DwoHcGF5bG9hZBgCIAEoCSp+Cg5GaWx0ZXJPcGVyYXRvchIJCgVFUVVBTBAA",
            "Eg0KCU5PVF9FUVVBTBABEgsKB0dSRUFURVIQAhIRCg1HUkVBVEVSX0VRVUFM",
            "EAMSCwoHU01BTExFUhAEEhEKDVNNQUxMRVJfRVFVQUwQBRIGCgJJThAGEgoK",
            "Bk5PVF9JThAHKjEKDkV4cGVyaW1lbnRUeXBlEg4KCkVYUEVSSU1FTlQQABIP",
            "CgtPQlNFUlZBVElPThABKlkKDEFCVGVzdFN0YXR1cxIKCgZVTktOT1cQABIJ",
            "CgVEUkFGVBABEgkKBURFQlVHEAISDQoJUFVCTElTSEVEEAMSCwoHU1RPUFBF",
            "RBAEEgsKB0FQUExJRUQQBSo7ChlBQlRlc3RGaWx0ZXJWYWx1ZVR5cGVFbnVt",
            "EgcKA0lOVBAAEgkKBUZMT0FUEAESCgoGU1RSSU5HEAJCWVozZ2l0aHViLmNv",
            "bS9GbHlEcmFnb25HTy9Qcm90b2J1ZkRlZmluaXRpb24vZ28vYWJ0ZXN0qgIh",
            "RHJhZ29uVTNEU0RLLk5ldHdvcmsuQVBJLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DragonU3DSDK.Network.API.Protocol.FilterOperator), typeof(global::DragonU3DSDK.Network.API.Protocol.ExperimentType), typeof(global::DragonU3DSDK.Network.API.Protocol.ABTestStatus), typeof(global::DragonU3DSDK.Network.API.Protocol.ABTestFilterValueTypeEnum), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ABTestFilter), global::DragonU3DSDK.Network.API.Protocol.ABTestFilter.Parser, new[]{ "Key", "Operator", "ValueType", "Value", "Values" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch), global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch.Parser, new[]{ "Filters" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ExperimentItem), global::DragonU3DSDK.Network.API.Protocol.ExperimentItem.Parser, new[]{ "Id", "Config", "Type", "WhiteList", "Applied" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ABTestItem), global::DragonU3DSDK.Network.API.Protocol.ABTestItem.Parser, new[]{ "Id", "App", "Name", "Desc", "FlowLimit", "AbtestCodename", "AnyMatches", "ExperimentItems", "LastEtag", "Status", "WhitelistMatchFilter", "CreatedAt", "UpdatedAt" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ABTestData), global::DragonU3DSDK.Network.API.Protocol.ABTestData.Parser, new[]{ "Group", "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum FilterOperator {
    /// <summary>
    /// 等于
    /// </summary>
    [pbr::OriginalName("EQUAL")] Equal = 0,
    /// <summary>
    /// 不等于
    /// </summary>
    [pbr::OriginalName("NOT_EQUAL")] NotEqual = 1,
    /// <summary>
    /// 大于
    /// </summary>
    [pbr::OriginalName("GREATER")] Greater = 2,
    /// <summary>
    /// 大于等于
    /// </summary>
    [pbr::OriginalName("GREATER_EQUAL")] GreaterEqual = 3,
    /// <summary>
    /// 小于
    /// </summary>
    [pbr::OriginalName("SMALLER")] Smaller = 4,
    /// <summary>
    /// 小于等于
    /// </summary>
    [pbr::OriginalName("SMALLER_EQUAL")] SmallerEqual = 5,
    /// <summary>
    /// 包含于
    /// </summary>
    [pbr::OriginalName("IN")] In = 6,
    /// <summary>
    /// 不包含于
    /// </summary>
    [pbr::OriginalName("NOT_IN")] NotIn = 7,
  }

  /// <summary>
  /// 实验组类型
  /// </summary>
  public enum ExperimentType {
    /// <summary>
    /// 实验组
    /// </summary>
    [pbr::OriginalName("EXPERIMENT")] Experiment = 0,
    /// <summary>
    /// 观察组
    /// </summary>
    [pbr::OriginalName("OBSERVATION")] Observation = 1,
  }

  /// <summary>
  /// ab测状态
  /// </summary>
  public enum ABTestStatus {
    [pbr::OriginalName("UNKNOW")] Unknow = 0,
    /// <summary>
    /// 草稿状态
    /// </summary>
    [pbr::OriginalName("DRAFT")] Draft = 1,
    /// <summary>
    /// 调试状态
    /// </summary>
    [pbr::OriginalName("DEBUG")] Debug = 2,
    /// <summary>
    /// 发布状态
    /// </summary>
    [pbr::OriginalName("PUBLISHED")] Published = 3,
    /// <summary>
    /// 停止状态
    /// </summary>
    [pbr::OriginalName("STOPPED")] Stopped = 4,
    /// <summary>
    /// 应用状态
    /// </summary>
    [pbr::OriginalName("APPLIED")] Applied = 5,
  }

  public enum ABTestFilterValueTypeEnum {
    [pbr::OriginalName("INT")] Int = 0,
    [pbr::OriginalName("FLOAT")] Float = 1,
    [pbr::OriginalName("STRING")] String = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// ab测单个条件
  /// </summary>
  public sealed partial class ABTestFilter : pb::IMessage<ABTestFilter> {
    private static readonly pb::MessageParser<ABTestFilter> _parser = new pb::MessageParser<ABTestFilter>(() => new ABTestFilter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ABTestFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.AbtestCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestFilter(ABTestFilter other) : this() {
      key_ = other.key_;
      operator_ = other.operator_;
      valueType_ = other.valueType_;
      value_ = other.value_;
      values_ = other.values_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestFilter Clone() {
      return new ABTestFilter(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    /// <summary>
    ///personas / header key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operator" field.</summary>
    public const int OperatorFieldNumber = 2;
    private global::DragonU3DSDK.Network.API.Protocol.FilterOperator operator_ = 0;
    /// <summary>
    /// 逻辑操作符
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.FilterOperator Operator {
      get { return operator_; }
      set {
        operator_ = value;
      }
    }

    /// <summary>Field number for the "value_type" field.</summary>
    public const int ValueTypeFieldNumber = 3;
    private global::DragonU3DSDK.Network.API.Protocol.ABTestFilterValueTypeEnum valueType_ = 0;
    /// <summary>
    /// 过滤用数据的数据类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.ABTestFilterValueTypeEnum ValueType {
      get { return valueType_; }
      set {
        valueType_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 4;
    private string value_ = "";
    /// <summary>
    /// 单一数据 服务于 其他比较条件
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "values" field.</summary>
    public const int ValuesFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_values_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> values_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// 列表数据 服务于 in / not_in
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Values {
      get { return values_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ABTestFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ABTestFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Operator != other.Operator) return false;
      if (ValueType != other.ValueType) return false;
      if (Value != other.Value) return false;
      if(!values_.Equals(other.values_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (Operator != 0) hash ^= Operator.GetHashCode();
      if (ValueType != 0) hash ^= ValueType.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      hash ^= values_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (Operator != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Operator);
      }
      if (ValueType != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ValueType);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Value);
      }
      values_.WriteTo(output, _repeated_values_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (Operator != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operator);
      }
      if (ValueType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ValueType);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      size += values_.CalculateSize(_repeated_values_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ABTestFilter other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.Operator != 0) {
        Operator = other.Operator;
      }
      if (other.ValueType != 0) {
        ValueType = other.ValueType;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      values_.Add(other.values_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 16: {
            Operator = (global::DragonU3DSDK.Network.API.Protocol.FilterOperator) input.ReadEnum();
            break;
          }
          case 24: {
            ValueType = (global::DragonU3DSDK.Network.API.Protocol.ABTestFilterValueTypeEnum) input.ReadEnum();
            break;
          }
          case 34: {
            Value = input.ReadString();
            break;
          }
          case 42: {
            values_.AddEntriesFrom(input, _repeated_values_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// ab测且条件
  /// </summary>
  public sealed partial class ABTestAllMatch : pb::IMessage<ABTestAllMatch> {
    private static readonly pb::MessageParser<ABTestAllMatch> _parser = new pb::MessageParser<ABTestAllMatch>(() => new ABTestAllMatch());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ABTestAllMatch> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.AbtestCommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestAllMatch() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestAllMatch(ABTestAllMatch other) : this() {
      filters_ = other.filters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestAllMatch Clone() {
      return new ABTestAllMatch(this);
    }

    /// <summary>Field number for the "filters" field.</summary>
    public const int FiltersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.ABTestFilter> _repeated_filters_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.ABTestFilter.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ABTestFilter> filters_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ABTestFilter>();
    /// <summary>
    /// 命中条件组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ABTestFilter> Filters {
      get { return filters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ABTestAllMatch);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ABTestAllMatch other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!filters_.Equals(other.filters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= filters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      filters_.WriteTo(output, _repeated_filters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += filters_.CalculateSize(_repeated_filters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ABTestAllMatch other) {
      if (other == null) {
        return;
      }
      filters_.Add(other.filters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            filters_.AddEntriesFrom(input, _repeated_filters_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 实验
  /// </summary>
  public sealed partial class ExperimentItem : pb::IMessage<ExperimentItem> {
    private static readonly pb::MessageParser<ExperimentItem> _parser = new pb::MessageParser<ExperimentItem>(() => new ExperimentItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExperimentItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.AbtestCommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExperimentItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExperimentItem(ExperimentItem other) : this() {
      id_ = other.id_;
      config_ = other.config_;
      type_ = other.type_;
      whiteList_ = other.whiteList_.Clone();
      applied_ = other.applied_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExperimentItem Clone() {
      return new ExperimentItem(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    /// <summary>
    ///实验id [也是实验顺序]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 2;
    private string config_ = "";
    /// <summary>
    /// 实验配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Config {
      get { return config_; }
      set {
        config_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 3;
    private global::DragonU3DSDK.Network.API.Protocol.ExperimentType type_ = 0;
    /// <summary>
    /// 实验类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.ExperimentType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "white_list" field.</summary>
    public const int WhiteListFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_whiteList_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> whiteList_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///白名单设备 device_ids
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> WhiteList {
      get { return whiteList_; }
    }

    /// <summary>Field number for the "applied" field.</summary>
    public const int AppliedFieldNumber = 5;
    private bool applied_;
    /// <summary>
    /// 是否被选为应用的实验组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Applied {
      get { return applied_; }
      set {
        applied_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExperimentItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExperimentItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Config != other.Config) return false;
      if (Type != other.Type) return false;
      if(!whiteList_.Equals(other.whiteList_)) return false;
      if (Applied != other.Applied) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Config.Length != 0) hash ^= Config.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      hash ^= whiteList_.GetHashCode();
      if (Applied != false) hash ^= Applied.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Config.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Config);
      }
      if (Type != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Type);
      }
      whiteList_.WriteTo(output, _repeated_whiteList_codec);
      if (Applied != false) {
        output.WriteRawTag(40);
        output.WriteBool(Applied);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Config.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Config);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += whiteList_.CalculateSize(_repeated_whiteList_codec);
      if (Applied != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExperimentItem other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Config.Length != 0) {
        Config = other.Config;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      whiteList_.Add(other.whiteList_);
      if (other.Applied != false) {
        Applied = other.Applied;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Config = input.ReadString();
            break;
          }
          case 24: {
            Type = (global::DragonU3DSDK.Network.API.Protocol.ExperimentType) input.ReadEnum();
            break;
          }
          case 34: {
            whiteList_.AddEntriesFrom(input, _repeated_whiteList_codec);
            break;
          }
          case 40: {
            Applied = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// ab测
  /// </summary>
  public sealed partial class ABTestItem : pb::IMessage<ABTestItem> {
    private static readonly pb::MessageParser<ABTestItem> _parser = new pb::MessageParser<ABTestItem>(() => new ABTestItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ABTestItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.AbtestCommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestItem(ABTestItem other) : this() {
      id_ = other.id_;
      app_ = other.app_;
      name_ = other.name_;
      desc_ = other.desc_;
      flowLimit_ = other.flowLimit_;
      abtestCodename_ = other.abtestCodename_;
      anyMatches_ = other.anyMatches_.Clone();
      experimentItems_ = other.experimentItems_.Clone();
      lastEtag_ = other.lastEtag_;
      status_ = other.status_;
      whitelistMatchFilter_ = other.whitelistMatchFilter_;
      createdAt_ = other.createdAt_;
      updatedAt_ = other.updatedAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestItem Clone() {
      return new ABTestItem(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// ab测id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "app" field.</summary>
    public const int AppFieldNumber = 2;
    private string app_ = "";
    /// <summary>
    /// app名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string App {
      get { return app_; }
      set {
        app_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    /// ab测名称 - 用户自己看的, 无限制
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 4;
    private string desc_ = "";
    /// <summary>
    /// ab测描述 - 用户自己看的, 无限制
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "flow_limit" field.</summary>
    public const int FlowLimitFieldNumber = 5;
    private uint flowLimit_;
    /// <summary>
    /// 流量控制 - 最大1000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FlowLimit {
      get { return flowLimit_; }
      set {
        flowLimit_ = value;
      }
    }

    /// <summary>Field number for the "abtest_codename" field.</summary>
    public const int AbtestCodenameFieldNumber = 6;
    private string abtestCodename_ = "";
    /// <summary>
    /// ab测代号 - 内容:[0-9 a-z A-Z _-] 长度: (0， 60]， 有可读性的和语义含义的内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AbtestCodename {
      get { return abtestCodename_; }
      set {
        abtestCodename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "any_matches" field.</summary>
    public const int AnyMatchesFieldNumber = 7;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch> _repeated_anyMatches_codec
        = pb::FieldCodec.ForMessage(58, global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch> anyMatches_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch>();
    /// <summary>
    /// ab测 任意条件组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ABTestAllMatch> AnyMatches {
      get { return anyMatches_; }
    }

    /// <summary>Field number for the "experiment_items" field.</summary>
    public const int ExperimentItemsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.ExperimentItem> _repeated_experimentItems_codec
        = pb::FieldCodec.ForMessage(66, global::DragonU3DSDK.Network.API.Protocol.ExperimentItem.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ExperimentItem> experimentItems_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ExperimentItem>();
    /// <summary>
    /// 实验组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ExperimentItem> ExperimentItems {
      get { return experimentItems_; }
    }

    /// <summary>Field number for the "last_etag" field.</summary>
    public const int LastEtagFieldNumber = 9;
    private string lastEtag_ = "";
    /// <summary>
    /// 最后修改的etag
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LastEtag {
      get { return lastEtag_; }
      set {
        lastEtag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 10;
    private global::DragonU3DSDK.Network.API.Protocol.ABTestStatus status_ = 0;
    /// <summary>
    /// ab测状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.ABTestStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "whitelist_match_filter" field.</summary>
    public const int WhitelistMatchFilterFieldNumber = 11;
    private bool whitelistMatchFilter_;
    /// <summary>
    /// 白名单是否需要匹配ABTestAllMatch
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool WhitelistMatchFilter {
      get { return whitelistMatchFilter_; }
      set {
        whitelistMatchFilter_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 12;
    private uint createdAt_;
    /// <summary>
    /// ab测创建时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 13;
    private uint updatedAt_;
    /// <summary>
    /// ab测更新时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ABTestItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ABTestItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (App != other.App) return false;
      if (Name != other.Name) return false;
      if (Desc != other.Desc) return false;
      if (FlowLimit != other.FlowLimit) return false;
      if (AbtestCodename != other.AbtestCodename) return false;
      if(!anyMatches_.Equals(other.anyMatches_)) return false;
      if(!experimentItems_.Equals(other.experimentItems_)) return false;
      if (LastEtag != other.LastEtag) return false;
      if (Status != other.Status) return false;
      if (WhitelistMatchFilter != other.WhitelistMatchFilter) return false;
      if (CreatedAt != other.CreatedAt) return false;
      if (UpdatedAt != other.UpdatedAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (App.Length != 0) hash ^= App.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (FlowLimit != 0) hash ^= FlowLimit.GetHashCode();
      if (AbtestCodename.Length != 0) hash ^= AbtestCodename.GetHashCode();
      hash ^= anyMatches_.GetHashCode();
      hash ^= experimentItems_.GetHashCode();
      if (LastEtag.Length != 0) hash ^= LastEtag.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (WhitelistMatchFilter != false) hash ^= WhitelistMatchFilter.GetHashCode();
      if (CreatedAt != 0) hash ^= CreatedAt.GetHashCode();
      if (UpdatedAt != 0) hash ^= UpdatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (App.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(App);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Desc);
      }
      if (FlowLimit != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FlowLimit);
      }
      if (AbtestCodename.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AbtestCodename);
      }
      anyMatches_.WriteTo(output, _repeated_anyMatches_codec);
      experimentItems_.WriteTo(output, _repeated_experimentItems_codec);
      if (LastEtag.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(LastEtag);
      }
      if (Status != 0) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Status);
      }
      if (WhitelistMatchFilter != false) {
        output.WriteRawTag(88);
        output.WriteBool(WhitelistMatchFilter);
      }
      if (CreatedAt != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(CreatedAt);
      }
      if (UpdatedAt != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(UpdatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (App.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(App);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (FlowLimit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FlowLimit);
      }
      if (AbtestCodename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AbtestCodename);
      }
      size += anyMatches_.CalculateSize(_repeated_anyMatches_codec);
      size += experimentItems_.CalculateSize(_repeated_experimentItems_codec);
      if (LastEtag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastEtag);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (WhitelistMatchFilter != false) {
        size += 1 + 1;
      }
      if (CreatedAt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CreatedAt);
      }
      if (UpdatedAt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UpdatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ABTestItem other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.App.Length != 0) {
        App = other.App;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.FlowLimit != 0) {
        FlowLimit = other.FlowLimit;
      }
      if (other.AbtestCodename.Length != 0) {
        AbtestCodename = other.AbtestCodename;
      }
      anyMatches_.Add(other.anyMatches_);
      experimentItems_.Add(other.experimentItems_);
      if (other.LastEtag.Length != 0) {
        LastEtag = other.LastEtag;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.WhitelistMatchFilter != false) {
        WhitelistMatchFilter = other.WhitelistMatchFilter;
      }
      if (other.CreatedAt != 0) {
        CreatedAt = other.CreatedAt;
      }
      if (other.UpdatedAt != 0) {
        UpdatedAt = other.UpdatedAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            App = input.ReadString();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            Desc = input.ReadString();
            break;
          }
          case 40: {
            FlowLimit = input.ReadUInt32();
            break;
          }
          case 50: {
            AbtestCodename = input.ReadString();
            break;
          }
          case 58: {
            anyMatches_.AddEntriesFrom(input, _repeated_anyMatches_codec);
            break;
          }
          case 66: {
            experimentItems_.AddEntriesFrom(input, _repeated_experimentItems_codec);
            break;
          }
          case 74: {
            LastEtag = input.ReadString();
            break;
          }
          case 80: {
            Status = (global::DragonU3DSDK.Network.API.Protocol.ABTestStatus) input.ReadEnum();
            break;
          }
          case 88: {
            WhitelistMatchFilter = input.ReadBool();
            break;
          }
          case 96: {
            CreatedAt = input.ReadUInt32();
            break;
          }
          case 104: {
            UpdatedAt = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端payload
  /// </summary>
  public sealed partial class ABTestData : pb::IMessage<ABTestData> {
    private static readonly pb::MessageParser<ABTestData> _parser = new pb::MessageParser<ABTestData>(() => new ABTestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ABTestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.AbtestCommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestData(ABTestData other) : this() {
      group_ = other.group_;
      payload_ = other.payload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ABTestData Clone() {
      return new ABTestData(this);
    }

    /// <summary>Field number for the "group" field.</summary>
    public const int GroupFieldNumber = 1;
    private string group_ = "";
    /// <summary>
    /// 实验组的Id(ExperimentItem.id)，对照组->0，实验组1->1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Group {
      get { return group_; }
      set {
        group_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private string payload_ = "";
    /// <summary>
    /// 具体配置载荷
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ABTestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ABTestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Group != other.Group) return false;
      if (Payload != other.Payload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Group.Length != 0) hash ^= Group.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Group.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Group);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Group.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Group);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ABTestData other) {
      if (other == null) {
        return;
      }
      if (other.Group.Length != 0) {
        Group = other.Group;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Group = input.ReadString();
            break;
          }
          case 18: {
            Payload = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
