// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: leaderboard_common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.Protocol {

  /// <summary>Holder for reflection information generated from leaderboard_common.proto</summary>
  public static partial class LeaderboardCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for leaderboard_common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LeaderboardCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhsZWFkZXJib2FyZF9jb21tb24ucHJvdG8iiAEKEExlYWRlcmJvYXJkRW50",
            "cnkSHAoUbGVhZGVyYm9hcmRfZW50cnlfaWQYASABKAkSDQoFc2NvcmUYAiAB",
            "KAQSDAoEcmFuaxgDIAEoBBINCgVleHRyYRgEIAEoCRISCgp1cGRhdGVkX2F0",
            "GAUgASgEEhYKDmxlYWRlcmJvYXJkX2lkGAYgASgJIkYKFExlYWRlcmJvYXJk",
            "RW50cnlMaXN0Ei4KE2xlYWRlcmJvYXJkX2VudHJpZXMYASADKAsyES5MZWFk",
            "ZXJib2FyZEVudHJ5IskBCg9MZWFkZXJib2FyZERhdGESGAoQbGVhZGVyYm9h",
            "cmRfdHlwZRgBIAEoCRINCgVzY29yZRgCIAEoCRINCgVleHRyYRgDIAEoCRI1",
            "Cgt1bmlxdWVfYXJncxgEIAMoCzIgLkxlYWRlcmJvYXJkRGF0YS5VbmlxdWVB",
            "cmdzRW50cnkSFAoMZ2xvYmFsX2V4dHJhGAUgASgJGjEKD1VuaXF1ZUFyZ3NF",
            "bnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIncKD0xlYWRl",
            "cmJvYXJkSW5mbxIWCg5sZWFkZXJib2FyZF9pZBgBIAEoCRIXCg91cGRhdGVf",
            "ZW5kX3RpbWUYAiABKAQSEAoIZW5kX3RpbWUYAyABKAQSDQoFZXh0cmEYBCAB",
            "KAkSEgoKY3JlYXRlZF9hdBgFIAEoBCKEAQoUTGVhZGVyYm9hcmRRdWVyeUl0",
            "ZW0SGAoQbGVhZGVyYm9hcmRfdHlwZRgBIAEoCRIOCgZvZmZzZXQYAiABKA0S",
            "DQoFY291bnQYAyABKA0SDAoEZGVzYxgEIAEoCBIlCgt1cGRhdGVfZGF0YRgF",
            "IAEoCzIQLkxlYWRlcmJvYXJkRGF0YSKkAQoTTGVhZGVyYm9hcmRMaXN0SXRl",
            "bRIuChNsZWFkZXJib2FyZF9lbnRyaWVzGAEgAygLMhEuTGVhZGVyYm9hcmRF",
            "bnRyeRIdCgJtZRgCIAEoCzIRLkxlYWRlcmJvYXJkRW50cnkSHgoEaW5mbxgD",
            "IAEoCzIQLkxlYWRlcmJvYXJkSW5mbxIeChZjdXJyZW50X2xlYWRlcmJvYXJk",
            "X2lkGAQgASgJImIKFUxlYWRlcmJvYXJkTWVJbmZvSXRlbRIdCgJtZRgBIAEo",
            "CzIRLkxlYWRlcmJvYXJkRW50cnkSKgoQbGVhZGVyYm9hcmRfaW5mbxgCIAEo",
            "CzIQLkxlYWRlcmJvYXJkSW5mb0KDAQojY29tLmRyYWdvbnBsdXMubmV0d29y",
            "ay5hcGkucHJvdG9jb2xaOGdpdGh1Yi5jb20vRmx5RHJhZ29uR08vUHJvdG9i",
            "dWZEZWZpbml0aW9uL2dvL2xlYWRlcmJvYXJkqgIhRHJhZ29uVTNEU0RLLk5l",
            "dHdvcmsuQVBJLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry), global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry.Parser, new[]{ "LeaderboardEntryId", "Score", "Rank", "Extra", "UpdatedAt", "LeaderboardId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntryList), global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntryList.Parser, new[]{ "LeaderboardEntries" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardData), global::DragonU3DSDK.Network.API.Protocol.LeaderboardData.Parser, new[]{ "LeaderboardType", "Score", "Extra", "UniqueArgs", "GlobalExtra" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo), global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo.Parser, new[]{ "LeaderboardId", "UpdateEndTime", "EndTime", "Extra", "CreatedAt" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardQueryItem), global::DragonU3DSDK.Network.API.Protocol.LeaderboardQueryItem.Parser, new[]{ "LeaderboardType", "Offset", "Count", "Desc", "UpdateData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardListItem), global::DragonU3DSDK.Network.API.Protocol.LeaderboardListItem.Parser, new[]{ "LeaderboardEntries", "Me", "Info", "CurrentLeaderboardId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.LeaderboardMeInfoItem), global::DragonU3DSDK.Network.API.Protocol.LeaderboardMeInfoItem.Parser, new[]{ "Me", "LeaderboardInfo" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 用于获取排行榜列表时，排行榜单条数据信息
  /// </summary>
  public sealed partial class LeaderboardEntry : pb::IMessage<LeaderboardEntry> {
    private static readonly pb::MessageParser<LeaderboardEntry> _parser = new pb::MessageParser<LeaderboardEntry>(() => new LeaderboardEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardEntry(LeaderboardEntry other) : this() {
      leaderboardEntryId_ = other.leaderboardEntryId_;
      score_ = other.score_;
      rank_ = other.rank_;
      extra_ = other.extra_;
      updatedAt_ = other.updatedAt_;
      leaderboardId_ = other.leaderboardId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardEntry Clone() {
      return new LeaderboardEntry(this);
    }

    /// <summary>Field number for the "leaderboard_entry_id" field.</summary>
    public const int LeaderboardEntryIdFieldNumber = 1;
    private string leaderboardEntryId_ = "";
    /// <summary>
    /// 排行榜数据标识ID（一般为玩家数字ID）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LeaderboardEntryId {
      get { return leaderboardEntryId_; }
      set {
        leaderboardEntryId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private ulong score_;
    /// <summary>
    /// 排行榜数据分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 3;
    private ulong rank_;
    /// <summary>
    /// 排行榜数据排名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "extra" field.</summary>
    public const int ExtraFieldNumber = 4;
    private string extra_ = "";
    /// <summary>
    /// 当前玩家除了分数以外，其余需要显示的信息，JSON字符串，例如:"{\"isRobot\":true,\"facebookName\":\"Hello Word\",\"facebookId\":\"123456789\",\"nickname\":\"Lucy\",\"avatar\":\"girl1\"}"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Extra {
      get { return extra_; }
      set {
        extra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 5;
    private ulong updatedAt_;
    /// <summary>
    /// 排行榜数据更新时间戳，单位(s)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    /// <summary>Field number for the "leaderboard_id" field.</summary>
    public const int LeaderboardIdFieldNumber = 6;
    private string leaderboardId_ = "";
    /// <summary>
    /// 当前玩家所在排行榜实例ID（若不在任何榜单，则为空值）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LeaderboardId {
      get { return leaderboardId_; }
      set {
        leaderboardId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderboardEntryId != other.LeaderboardEntryId) return false;
      if (Score != other.Score) return false;
      if (Rank != other.Rank) return false;
      if (Extra != other.Extra) return false;
      if (UpdatedAt != other.UpdatedAt) return false;
      if (LeaderboardId != other.LeaderboardId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderboardEntryId.Length != 0) hash ^= LeaderboardEntryId.GetHashCode();
      if (Score != 0UL) hash ^= Score.GetHashCode();
      if (Rank != 0UL) hash ^= Rank.GetHashCode();
      if (Extra.Length != 0) hash ^= Extra.GetHashCode();
      if (UpdatedAt != 0UL) hash ^= UpdatedAt.GetHashCode();
      if (LeaderboardId.Length != 0) hash ^= LeaderboardId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LeaderboardEntryId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LeaderboardEntryId);
      }
      if (Score != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Score);
      }
      if (Rank != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Rank);
      }
      if (Extra.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Extra);
      }
      if (UpdatedAt != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(UpdatedAt);
      }
      if (LeaderboardId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(LeaderboardId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LeaderboardEntryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LeaderboardEntryId);
      }
      if (Score != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Score);
      }
      if (Rank != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Rank);
      }
      if (Extra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Extra);
      }
      if (UpdatedAt != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UpdatedAt);
      }
      if (LeaderboardId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LeaderboardId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardEntry other) {
      if (other == null) {
        return;
      }
      if (other.LeaderboardEntryId.Length != 0) {
        LeaderboardEntryId = other.LeaderboardEntryId;
      }
      if (other.Score != 0UL) {
        Score = other.Score;
      }
      if (other.Rank != 0UL) {
        Rank = other.Rank;
      }
      if (other.Extra.Length != 0) {
        Extra = other.Extra;
      }
      if (other.UpdatedAt != 0UL) {
        UpdatedAt = other.UpdatedAt;
      }
      if (other.LeaderboardId.Length != 0) {
        LeaderboardId = other.LeaderboardId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LeaderboardEntryId = input.ReadString();
            break;
          }
          case 16: {
            Score = input.ReadUInt64();
            break;
          }
          case 24: {
            Rank = input.ReadUInt64();
            break;
          }
          case 34: {
            Extra = input.ReadString();
            break;
          }
          case 40: {
            UpdatedAt = input.ReadUInt64();
            break;
          }
          case 50: {
            LeaderboardId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LeaderboardEntryList : pb::IMessage<LeaderboardEntryList> {
    private static readonly pb::MessageParser<LeaderboardEntryList> _parser = new pb::MessageParser<LeaderboardEntryList>(() => new LeaderboardEntryList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardEntryList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardEntryList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardEntryList(LeaderboardEntryList other) : this() {
      leaderboardEntries_ = other.leaderboardEntries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardEntryList Clone() {
      return new LeaderboardEntryList(this);
    }

    /// <summary>Field number for the "leaderboard_entries" field.</summary>
    public const int LeaderboardEntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry> _repeated_leaderboardEntries_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry> leaderboardEntries_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry> LeaderboardEntries {
      get { return leaderboardEntries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardEntryList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardEntryList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!leaderboardEntries_.Equals(other.leaderboardEntries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= leaderboardEntries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      leaderboardEntries_.WriteTo(output, _repeated_leaderboardEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += leaderboardEntries_.CalculateSize(_repeated_leaderboardEntries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardEntryList other) {
      if (other == null) {
        return;
      }
      leaderboardEntries_.Add(other.leaderboardEntries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            leaderboardEntries_.AddEntriesFrom(input, _repeated_leaderboardEntries_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 用于更新排行榜分数时传入
  /// </summary>
  public sealed partial class LeaderboardData : pb::IMessage<LeaderboardData> {
    private static readonly pb::MessageParser<LeaderboardData> _parser = new pb::MessageParser<LeaderboardData>(() => new LeaderboardData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardData(LeaderboardData other) : this() {
      leaderboardType_ = other.leaderboardType_;
      score_ = other.score_;
      extra_ = other.extra_;
      uniqueArgs_ = other.uniqueArgs_.Clone();
      globalExtra_ = other.globalExtra_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardData Clone() {
      return new LeaderboardData(this);
    }

    /// <summary>Field number for the "leaderboard_type" field.</summary>
    public const int LeaderboardTypeFieldNumber = 1;
    private string leaderboardType_ = "";
    /// <summary>
    /// 排行榜类型标识（例如关卡榜，level_board等，由调用方自行决定排行榜类型标识）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LeaderboardType {
      get { return leaderboardType_; }
      set {
        leaderboardType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private string score_ = "";
    /// <summary>
    /// 当前玩家目前分数（关卡榜，则可能为打过多少关，记多少分；收集榜，可能为收集了多少东西，记多少分；具体看需求规则）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Score {
      get { return score_; }
      set {
        score_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "extra" field.</summary>
    public const int ExtraFieldNumber = 3;
    private string extra_ = "";
    /// <summary>
    /// 当前玩家除了分数以外，其余需要显示的信息；JSON字符串形式，例如玩家个人信息，则为"{\"nickname\":\"Lucy\",\"avatar\":\"girl1\"}"等等；具体以调用方自行所需要的信息为主，键名不做限制，服务端仅存储与下发，无任何逻辑参与
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Extra {
      get { return extra_; }
      set {
        extra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unique_args" field.</summary>
    public const int UniqueArgsFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_uniqueArgs_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 34);
    private readonly pbc::MapField<string, string> uniqueArgs_ = new pbc::MapField<string, string>();
    /// <summary>
    /// 同类型内的排行榜标识参数（参数强一致相同的才能入同一个榜单）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> UniqueArgs {
      get { return uniqueArgs_; }
    }

    /// <summary>Field number for the "global_extra" field.</summary>
    public const int GlobalExtraFieldNumber = 5;
    private string globalExtra_ = "";
    /// <summary>
    /// 透传参数 json字符串（存入排行榜实例配置，全榜通用数值，自定义，不参与服务端逻辑，由第一个建榜玩家携带的数据为准进行保存）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GlobalExtra {
      get { return globalExtra_; }
      set {
        globalExtra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderboardType != other.LeaderboardType) return false;
      if (Score != other.Score) return false;
      if (Extra != other.Extra) return false;
      if (!UniqueArgs.Equals(other.UniqueArgs)) return false;
      if (GlobalExtra != other.GlobalExtra) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderboardType.Length != 0) hash ^= LeaderboardType.GetHashCode();
      if (Score.Length != 0) hash ^= Score.GetHashCode();
      if (Extra.Length != 0) hash ^= Extra.GetHashCode();
      hash ^= UniqueArgs.GetHashCode();
      if (GlobalExtra.Length != 0) hash ^= GlobalExtra.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LeaderboardType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LeaderboardType);
      }
      if (Score.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Score);
      }
      if (Extra.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Extra);
      }
      uniqueArgs_.WriteTo(output, _map_uniqueArgs_codec);
      if (GlobalExtra.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GlobalExtra);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LeaderboardType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LeaderboardType);
      }
      if (Score.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Score);
      }
      if (Extra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Extra);
      }
      size += uniqueArgs_.CalculateSize(_map_uniqueArgs_codec);
      if (GlobalExtra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GlobalExtra);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardData other) {
      if (other == null) {
        return;
      }
      if (other.LeaderboardType.Length != 0) {
        LeaderboardType = other.LeaderboardType;
      }
      if (other.Score.Length != 0) {
        Score = other.Score;
      }
      if (other.Extra.Length != 0) {
        Extra = other.Extra;
      }
      uniqueArgs_.Add(other.uniqueArgs_);
      if (other.GlobalExtra.Length != 0) {
        GlobalExtra = other.GlobalExtra;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LeaderboardType = input.ReadString();
            break;
          }
          case 18: {
            Score = input.ReadString();
            break;
          }
          case 26: {
            Extra = input.ReadString();
            break;
          }
          case 34: {
            uniqueArgs_.AddEntriesFrom(input, _map_uniqueArgs_codec);
            break;
          }
          case 42: {
            GlobalExtra = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 用于下发当前玩家所在排行榜的实例信息
  /// </summary>
  public sealed partial class LeaderboardInfo : pb::IMessage<LeaderboardInfo> {
    private static readonly pb::MessageParser<LeaderboardInfo> _parser = new pb::MessageParser<LeaderboardInfo>(() => new LeaderboardInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardInfo(LeaderboardInfo other) : this() {
      leaderboardId_ = other.leaderboardId_;
      updateEndTime_ = other.updateEndTime_;
      endTime_ = other.endTime_;
      extra_ = other.extra_;
      createdAt_ = other.createdAt_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardInfo Clone() {
      return new LeaderboardInfo(this);
    }

    /// <summary>Field number for the "leaderboard_id" field.</summary>
    public const int LeaderboardIdFieldNumber = 1;
    private string leaderboardId_ = "";
    /// <summary>
    /// 排行榜实例ID（唯一标识一个排行榜实例）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LeaderboardId {
      get { return leaderboardId_; }
      set {
        leaderboardId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "update_end_time" field.</summary>
    public const int UpdateEndTimeFieldNumber = 2;
    private ulong updateEndTime_;
    /// <summary>
    /// 排行榜结束更新分数的时间戳，若无时间限制则为0（毫秒）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UpdateEndTime {
      get { return updateEndTime_; }
      set {
        updateEndTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 3;
    private ulong endTime_;
    /// <summary>
    /// 排行榜完全结束的时间戳，若无时间限制则为0（毫秒，PS:某些类型的排行榜会新增排行榜实例）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "extra" field.</summary>
    public const int ExtraFieldNumber = 4;
    private string extra_ = "";
    /// <summary>
    /// 其余所需透传的排行榜实例全榜数值信息（json字符串，各类型排行榜可以不一样，灵活使用，默认值为空字符串）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Extra {
      get { return extra_; }
      set {
        extra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 5;
    private ulong createdAt_;
    /// <summary>
    /// 排行榜创建时间戳
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderboardId != other.LeaderboardId) return false;
      if (UpdateEndTime != other.UpdateEndTime) return false;
      if (EndTime != other.EndTime) return false;
      if (Extra != other.Extra) return false;
      if (CreatedAt != other.CreatedAt) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderboardId.Length != 0) hash ^= LeaderboardId.GetHashCode();
      if (UpdateEndTime != 0UL) hash ^= UpdateEndTime.GetHashCode();
      if (EndTime != 0UL) hash ^= EndTime.GetHashCode();
      if (Extra.Length != 0) hash ^= Extra.GetHashCode();
      if (CreatedAt != 0UL) hash ^= CreatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LeaderboardId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LeaderboardId);
      }
      if (UpdateEndTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(UpdateEndTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(EndTime);
      }
      if (Extra.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Extra);
      }
      if (CreatedAt != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(CreatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LeaderboardId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LeaderboardId);
      }
      if (UpdateEndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UpdateEndTime);
      }
      if (EndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EndTime);
      }
      if (Extra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Extra);
      }
      if (CreatedAt != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CreatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardInfo other) {
      if (other == null) {
        return;
      }
      if (other.LeaderboardId.Length != 0) {
        LeaderboardId = other.LeaderboardId;
      }
      if (other.UpdateEndTime != 0UL) {
        UpdateEndTime = other.UpdateEndTime;
      }
      if (other.EndTime != 0UL) {
        EndTime = other.EndTime;
      }
      if (other.Extra.Length != 0) {
        Extra = other.Extra;
      }
      if (other.CreatedAt != 0UL) {
        CreatedAt = other.CreatedAt;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LeaderboardId = input.ReadString();
            break;
          }
          case 16: {
            UpdateEndTime = input.ReadUInt64();
            break;
          }
          case 24: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 34: {
            Extra = input.ReadString();
            break;
          }
          case 40: {
            CreatedAt = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 用于获取排行榜列表信息时传入
  /// </summary>
  public sealed partial class LeaderboardQueryItem : pb::IMessage<LeaderboardQueryItem> {
    private static readonly pb::MessageParser<LeaderboardQueryItem> _parser = new pb::MessageParser<LeaderboardQueryItem>(() => new LeaderboardQueryItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardQueryItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardQueryItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardQueryItem(LeaderboardQueryItem other) : this() {
      leaderboardType_ = other.leaderboardType_;
      offset_ = other.offset_;
      count_ = other.count_;
      desc_ = other.desc_;
      updateData_ = other.updateData_ != null ? other.updateData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardQueryItem Clone() {
      return new LeaderboardQueryItem(this);
    }

    /// <summary>Field number for the "leaderboard_type" field.</summary>
    public const int LeaderboardTypeFieldNumber = 1;
    private string leaderboardType_ = "";
    /// <summary>
    /// 排行榜类型标识（例如关卡榜，level_board等，由调用方自行决定排行榜类型标识）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LeaderboardType {
      get { return leaderboardType_; }
      set {
        leaderboardType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 2;
    private uint offset_;
    /// <summary>
    /// 排行榜数据分页offset，默认为0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 3;
    private uint count_;
    /// <summary>
    /// 排行榜数据分页页条数，默认为50
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 4;
    private bool desc_;
    /// <summary>
    /// 是否为排行榜倒序，false：分数由高到低排列，true：分数由低到高排列
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Desc {
      get { return desc_; }
      set {
        desc_ = value;
      }
    }

    /// <summary>Field number for the "update_data" field.</summary>
    public const int UpdateDataFieldNumber = 5;
    private global::DragonU3DSDK.Network.API.Protocol.LeaderboardData updateData_;
    /// <summary>
    /// 同时设置需要更新入榜的当前玩家排行榜分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.LeaderboardData UpdateData {
      get { return updateData_; }
      set {
        updateData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardQueryItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardQueryItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderboardType != other.LeaderboardType) return false;
      if (Offset != other.Offset) return false;
      if (Count != other.Count) return false;
      if (Desc != other.Desc) return false;
      if (!object.Equals(UpdateData, other.UpdateData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderboardType.Length != 0) hash ^= LeaderboardType.GetHashCode();
      if (Offset != 0) hash ^= Offset.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      if (Desc != false) hash ^= Desc.GetHashCode();
      if (updateData_ != null) hash ^= UpdateData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LeaderboardType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LeaderboardType);
      }
      if (Offset != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Offset);
      }
      if (Count != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Count);
      }
      if (Desc != false) {
        output.WriteRawTag(32);
        output.WriteBool(Desc);
      }
      if (updateData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(UpdateData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LeaderboardType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LeaderboardType);
      }
      if (Offset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Offset);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Count);
      }
      if (Desc != false) {
        size += 1 + 1;
      }
      if (updateData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardQueryItem other) {
      if (other == null) {
        return;
      }
      if (other.LeaderboardType.Length != 0) {
        LeaderboardType = other.LeaderboardType;
      }
      if (other.Offset != 0) {
        Offset = other.Offset;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      if (other.Desc != false) {
        Desc = other.Desc;
      }
      if (other.updateData_ != null) {
        if (updateData_ == null) {
          UpdateData = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardData();
        }
        UpdateData.MergeFrom(other.UpdateData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LeaderboardType = input.ReadString();
            break;
          }
          case 16: {
            Offset = input.ReadUInt32();
            break;
          }
          case 24: {
            Count = input.ReadUInt32();
            break;
          }
          case 32: {
            Desc = input.ReadBool();
            break;
          }
          case 42: {
            if (updateData_ == null) {
              UpdateData = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardData();
            }
            input.ReadMessage(UpdateData);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 用于获取排行榜列表信息，响应数据内的元素结构
  /// </summary>
  public sealed partial class LeaderboardListItem : pb::IMessage<LeaderboardListItem> {
    private static readonly pb::MessageParser<LeaderboardListItem> _parser = new pb::MessageParser<LeaderboardListItem>(() => new LeaderboardListItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardListItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardListItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardListItem(LeaderboardListItem other) : this() {
      leaderboardEntries_ = other.leaderboardEntries_.Clone();
      me_ = other.me_ != null ? other.me_.Clone() : null;
      info_ = other.info_ != null ? other.info_.Clone() : null;
      currentLeaderboardId_ = other.currentLeaderboardId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardListItem Clone() {
      return new LeaderboardListItem(this);
    }

    /// <summary>Field number for the "leaderboard_entries" field.</summary>
    public const int LeaderboardEntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry> _repeated_leaderboardEntries_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry> leaderboardEntries_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry>();
    /// <summary>
    /// 所查排行榜列表数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry> LeaderboardEntries {
      get { return leaderboardEntries_; }
    }

    /// <summary>Field number for the "me" field.</summary>
    public const int MeFieldNumber = 2;
    private global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry me_;
    /// <summary>
    /// 当前玩家在排行榜内的数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry Me {
      get { return me_; }
      set {
        me_ = value;
      }
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 3;
    private global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo info_;
    /// <summary>
    /// 所查排行榜的其他实例信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "current_leaderboard_id" field.</summary>
    public const int CurrentLeaderboardIdFieldNumber = 4;
    private string currentLeaderboardId_ = "";
    /// <summary>
    /// 当前类型的排行榜有效（未达到限制的）排行榜实例ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CurrentLeaderboardId {
      get { return currentLeaderboardId_; }
      set {
        currentLeaderboardId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardListItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardListItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!leaderboardEntries_.Equals(other.leaderboardEntries_)) return false;
      if (!object.Equals(Me, other.Me)) return false;
      if (!object.Equals(Info, other.Info)) return false;
      if (CurrentLeaderboardId != other.CurrentLeaderboardId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= leaderboardEntries_.GetHashCode();
      if (me_ != null) hash ^= Me.GetHashCode();
      if (info_ != null) hash ^= Info.GetHashCode();
      if (CurrentLeaderboardId.Length != 0) hash ^= CurrentLeaderboardId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      leaderboardEntries_.WriteTo(output, _repeated_leaderboardEntries_codec);
      if (me_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Me);
      }
      if (info_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Info);
      }
      if (CurrentLeaderboardId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CurrentLeaderboardId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += leaderboardEntries_.CalculateSize(_repeated_leaderboardEntries_codec);
      if (me_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Me);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (CurrentLeaderboardId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentLeaderboardId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardListItem other) {
      if (other == null) {
        return;
      }
      leaderboardEntries_.Add(other.leaderboardEntries_);
      if (other.me_ != null) {
        if (me_ == null) {
          Me = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry();
        }
        Me.MergeFrom(other.Me);
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo();
        }
        Info.MergeFrom(other.Info);
      }
      if (other.CurrentLeaderboardId.Length != 0) {
        CurrentLeaderboardId = other.CurrentLeaderboardId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            leaderboardEntries_.AddEntriesFrom(input, _repeated_leaderboardEntries_codec);
            break;
          }
          case 18: {
            if (me_ == null) {
              Me = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry();
            }
            input.ReadMessage(Me);
            break;
          }
          case 26: {
            if (info_ == null) {
              Info = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 34: {
            CurrentLeaderboardId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 用户获取当前玩家所在多个排行榜的排行榜分数数据以及排行榜配置数据
  /// </summary>
  public sealed partial class LeaderboardMeInfoItem : pb::IMessage<LeaderboardMeInfoItem> {
    private static readonly pb::MessageParser<LeaderboardMeInfoItem> _parser = new pb::MessageParser<LeaderboardMeInfoItem>(() => new LeaderboardMeInfoItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaderboardMeInfoItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.LeaderboardCommonReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardMeInfoItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardMeInfoItem(LeaderboardMeInfoItem other) : this() {
      me_ = other.me_ != null ? other.me_.Clone() : null;
      leaderboardInfo_ = other.leaderboardInfo_ != null ? other.leaderboardInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaderboardMeInfoItem Clone() {
      return new LeaderboardMeInfoItem(this);
    }

    /// <summary>Field number for the "me" field.</summary>
    public const int MeFieldNumber = 1;
    private global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry me_;
    /// <summary>
    /// 当前玩家在排行榜内的数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry Me {
      get { return me_; }
      set {
        me_ = value;
      }
    }

    /// <summary>Field number for the "leaderboard_info" field.</summary>
    public const int LeaderboardInfoFieldNumber = 2;
    private global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo leaderboardInfo_;
    /// <summary>
    /// 当前排行榜的其他实例信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo LeaderboardInfo {
      get { return leaderboardInfo_; }
      set {
        leaderboardInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaderboardMeInfoItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaderboardMeInfoItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Me, other.Me)) return false;
      if (!object.Equals(LeaderboardInfo, other.LeaderboardInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (me_ != null) hash ^= Me.GetHashCode();
      if (leaderboardInfo_ != null) hash ^= LeaderboardInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (me_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Me);
      }
      if (leaderboardInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeaderboardInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (me_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Me);
      }
      if (leaderboardInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaderboardInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaderboardMeInfoItem other) {
      if (other == null) {
        return;
      }
      if (other.me_ != null) {
        if (me_ == null) {
          Me = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry();
        }
        Me.MergeFrom(other.Me);
      }
      if (other.leaderboardInfo_ != null) {
        if (leaderboardInfo_ == null) {
          LeaderboardInfo = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo();
        }
        LeaderboardInfo.MergeFrom(other.LeaderboardInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (me_ == null) {
              Me = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardEntry();
            }
            input.ReadMessage(Me);
            break;
          }
          case 18: {
            if (leaderboardInfo_ == null) {
              LeaderboardInfo = new global::DragonU3DSDK.Network.API.Protocol.LeaderboardInfo();
            }
            input.ReadMessage(LeaderboardInfo);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
