// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: activity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.Protocol {

  /// <summary>Holder for reflection information generated from activity.proto</summary>
  public static partial class ActivityReflection {

    #region Descriptor
    /// <summary>File descriptor for activity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActivityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5hY3Rpdml0eS5wcm90bxoMY29tbW9uLnByb3RvIrQBCghBY3Rpdml0eRIT",
            "CgthY3Rpdml0eV9pZBgBIAEoCRIVCg1hY3Rpdml0eV90eXBlGAIgASgJEhIK",
            "CnN0YXJ0X3RpbWUYAyABKAQSEAoIZW5kX3RpbWUYBCABKAQSFwoPcmV3YXJk",
            "X2VuZF90aW1lGAUgASgEEg4KBmNvbmZpZxgGIAEoCRISCgptYW51YWxfZW5k",
            "GAcgASgIEhkKEWFjdGl2aXR5X3N1Yl90eXBlGAggASgJIpgCCgtSZXNBY3Rp",
            "dml0eRITCgthY3Rpdml0eV9pZBgBIAEoCRIVCg1hY3Rpdml0eV90eXBlGAIg",
            "ASgJEhIKCnN0YXJ0X3RpbWUYAyABKAQSEAoIZW5kX3RpbWUYBCABKAQSFwoP",
            "cmV3YXJkX2VuZF90aW1lGAUgASgEEg4KBmNvbmZpZxgGIAEoCRISCgptYW51",
            "YWxfZW5kGAcgASgIEhUKDXJlc291cmNlX3BhdGgYCCADKAkSGQoRYWN0aXZp",
            "dHlfc3ViX3R5cGUYCSABKAkSJAoNYWN0aXZpdHlfbW9kZRgKIAEoDjINLkFj",
            "dGl2aXR5TW9kZRIRCgl1c2VyX2RhdGEYCyABKAkSDwoHaXNfdGVzdBgMIAEo",
            "CCIQCg5DR2V0QWN0aXZpdGllcyIvCg5TR2V0QWN0aXZpdGllcxIdCgphY3Rp",
            "dml0aWVzGAEgAygLMgkuQWN0aXZpdHki0AEKEUNHZXRSZXNBY3Rpdml0aWVz",
            "EhsKCHBsYXRmb3JtGAEgASgOMgkuUGxhdGZvcm0SEwoHdmVyc2lvbhgCIAEo",
            "BEICGAESPQoOYWN0aXZpdHlfdHlwZXMYAyADKAsyJS5DR2V0UmVzQWN0aXZp",
            "dGllcy5BY3Rpdml0eVR5cGVzRW50cnkSFAoMYWR2YW5jZV9kYXlzGAQgASgN",
            "GjQKEkFjdGl2aXR5VHlwZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUY",
            "AiABKAk6AjgBIjUKEVNHZXRSZXNBY3Rpdml0aWVzEiAKCmFjdGl2aXRpZXMY",
            "ASADKAsyDC5SZXNBY3Rpdml0eSJkCgxBY3Rpdml0eVRpbWUSFQoNYWN0aXZp",
            "dHlfdHlwZRgBIAEoCRISCgpzdGFydF90aW1lGAIgASgDEhAKCGVuZF90aW1l",
            "GAMgASgDEhcKD3Jld2FyZF9lbmRfdGltZRgEIAEoAyIrChFDR2V0QWN0aXZp",
            "dHlUaW1lcxIWCg5hY3Rpdml0eV90eXBlcxgBIAMoCSI2ChFTR2V0QWN0aXZp",
            "dHlUaW1lcxIhCgphY3Rpdml0aWVzGAEgAygLMg0uQWN0aXZpdHlUaW1lKjMK",
            "DEFjdGl2aXR5TW9kZRISCg5PUEVSQVRJTkdfTU9ERRAAEg8KC0NVU1RPTV9N",
            "T0RFEAFCVAojY29tLmRyYWdvbnBsdXMubmV0d29yay5hcGkucHJvdG9jb2xa",
            "CXByb3RvY29sc6oCIURyYWdvblUzRFNESy5OZXR3b3JrLkFQSS5Qcm90b2Nv",
            "bGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DragonU3DSDK.Network.API.Protocol.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DragonU3DSDK.Network.API.Protocol.ActivityMode), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.Activity), global::DragonU3DSDK.Network.API.Protocol.Activity.Parser, new[]{ "ActivityId", "ActivityType", "StartTime", "EndTime", "RewardEndTime", "Config", "ManualEnd", "ActivitySubType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ResActivity), global::DragonU3DSDK.Network.API.Protocol.ResActivity.Parser, new[]{ "ActivityId", "ActivityType", "StartTime", "EndTime", "RewardEndTime", "Config", "ManualEnd", "ResourcePath", "ActivitySubType", "ActivityMode", "UserData", "IsTest" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CGetActivities), global::DragonU3DSDK.Network.API.Protocol.CGetActivities.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SGetActivities), global::DragonU3DSDK.Network.API.Protocol.SGetActivities.Parser, new[]{ "Activities" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CGetResActivities), global::DragonU3DSDK.Network.API.Protocol.CGetResActivities.Parser, new[]{ "Platform", "Version", "ActivityTypes", "AdvanceDays" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SGetResActivities), global::DragonU3DSDK.Network.API.Protocol.SGetResActivities.Parser, new[]{ "Activities" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ActivityTime), global::DragonU3DSDK.Network.API.Protocol.ActivityTime.Parser, new[]{ "ActivityType", "StartTime", "EndTime", "RewardEndTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CGetActivityTimes), global::DragonU3DSDK.Network.API.Protocol.CGetActivityTimes.Parser, new[]{ "ActivityTypes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SGetActivityTimes), global::DragonU3DSDK.Network.API.Protocol.SGetActivityTimes.Parser, new[]{ "Activities" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ActivityMode {
    /// <summary>
    /// 默认值，后台策划活动内根据时间范围进行排期的活动
    /// </summary>
    [pbr::OriginalName("OPERATING_MODE")] OperatingMode = 0,
    /// <summary>
    /// 自定义活动（即某些项目的包内自定义活动，根据类型获取，无需时间数值）
    /// </summary>
    [pbr::OriginalName("CUSTOM_MODE")] CustomMode = 1,
  }

  #endregion

  #region Messages
  public sealed partial class Activity : pb::IMessage<Activity> {
    private static readonly pb::MessageParser<Activity> _parser = new pb::MessageParser<Activity>(() => new Activity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Activity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Activity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Activity(Activity other) : this() {
      activityId_ = other.activityId_;
      activityType_ = other.activityType_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      rewardEndTime_ = other.rewardEndTime_;
      config_ = other.config_;
      manualEnd_ = other.manualEnd_;
      activitySubType_ = other.activitySubType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Activity Clone() {
      return new Activity(this);
    }

    /// <summary>Field number for the "activity_id" field.</summary>
    public const int ActivityIdFieldNumber = 1;
    private string activityId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityId {
      get { return activityId_; }
      set {
        activityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "activity_type" field.</summary>
    public const int ActivityTypeFieldNumber = 2;
    private string activityType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityType {
      get { return activityType_; }
      set {
        activityType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 3;
    private ulong startTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 4;
    private ulong endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "reward_end_time" field.</summary>
    public const int RewardEndTimeFieldNumber = 5;
    private ulong rewardEndTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong RewardEndTime {
      get { return rewardEndTime_; }
      set {
        rewardEndTime_ = value;
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 6;
    private string config_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Config {
      get { return config_; }
      set {
        config_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "manual_end" field.</summary>
    public const int ManualEndFieldNumber = 7;
    private bool manualEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ManualEnd {
      get { return manualEnd_; }
      set {
        manualEnd_ = value;
      }
    }

    /// <summary>Field number for the "activity_sub_type" field.</summary>
    public const int ActivitySubTypeFieldNumber = 8;
    private string activitySubType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivitySubType {
      get { return activitySubType_; }
      set {
        activitySubType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Activity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Activity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActivityId != other.ActivityId) return false;
      if (ActivityType != other.ActivityType) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (RewardEndTime != other.RewardEndTime) return false;
      if (Config != other.Config) return false;
      if (ManualEnd != other.ManualEnd) return false;
      if (ActivitySubType != other.ActivitySubType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActivityId.Length != 0) hash ^= ActivityId.GetHashCode();
      if (ActivityType.Length != 0) hash ^= ActivityType.GetHashCode();
      if (StartTime != 0UL) hash ^= StartTime.GetHashCode();
      if (EndTime != 0UL) hash ^= EndTime.GetHashCode();
      if (RewardEndTime != 0UL) hash ^= RewardEndTime.GetHashCode();
      if (Config.Length != 0) hash ^= Config.GetHashCode();
      if (ManualEnd != false) hash ^= ManualEnd.GetHashCode();
      if (ActivitySubType.Length != 0) hash ^= ActivitySubType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActivityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActivityId);
      }
      if (ActivityType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ActivityType);
      }
      if (StartTime != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(StartTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(EndTime);
      }
      if (RewardEndTime != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(RewardEndTime);
      }
      if (Config.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Config);
      }
      if (ManualEnd != false) {
        output.WriteRawTag(56);
        output.WriteBool(ManualEnd);
      }
      if (ActivitySubType.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ActivitySubType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActivityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityId);
      }
      if (ActivityType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityType);
      }
      if (StartTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartTime);
      }
      if (EndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EndTime);
      }
      if (RewardEndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RewardEndTime);
      }
      if (Config.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Config);
      }
      if (ManualEnd != false) {
        size += 1 + 1;
      }
      if (ActivitySubType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivitySubType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Activity other) {
      if (other == null) {
        return;
      }
      if (other.ActivityId.Length != 0) {
        ActivityId = other.ActivityId;
      }
      if (other.ActivityType.Length != 0) {
        ActivityType = other.ActivityType;
      }
      if (other.StartTime != 0UL) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0UL) {
        EndTime = other.EndTime;
      }
      if (other.RewardEndTime != 0UL) {
        RewardEndTime = other.RewardEndTime;
      }
      if (other.Config.Length != 0) {
        Config = other.Config;
      }
      if (other.ManualEnd != false) {
        ManualEnd = other.ManualEnd;
      }
      if (other.ActivitySubType.Length != 0) {
        ActivitySubType = other.ActivitySubType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ActivityId = input.ReadString();
            break;
          }
          case 18: {
            ActivityType = input.ReadString();
            break;
          }
          case 24: {
            StartTime = input.ReadUInt64();
            break;
          }
          case 32: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 40: {
            RewardEndTime = input.ReadUInt64();
            break;
          }
          case 50: {
            Config = input.ReadString();
            break;
          }
          case 56: {
            ManualEnd = input.ReadBool();
            break;
          }
          case 66: {
            ActivitySubType = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResActivity : pb::IMessage<ResActivity> {
    private static readonly pb::MessageParser<ResActivity> _parser = new pb::MessageParser<ResActivity>(() => new ResActivity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResActivity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResActivity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResActivity(ResActivity other) : this() {
      activityId_ = other.activityId_;
      activityType_ = other.activityType_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      rewardEndTime_ = other.rewardEndTime_;
      config_ = other.config_;
      manualEnd_ = other.manualEnd_;
      resourcePath_ = other.resourcePath_.Clone();
      activitySubType_ = other.activitySubType_;
      activityMode_ = other.activityMode_;
      userData_ = other.userData_;
      isTest_ = other.isTest_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResActivity Clone() {
      return new ResActivity(this);
    }

    /// <summary>Field number for the "activity_id" field.</summary>
    public const int ActivityIdFieldNumber = 1;
    private string activityId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityId {
      get { return activityId_; }
      set {
        activityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "activity_type" field.</summary>
    public const int ActivityTypeFieldNumber = 2;
    private string activityType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityType {
      get { return activityType_; }
      set {
        activityType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 3;
    private ulong startTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 4;
    private ulong endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "reward_end_time" field.</summary>
    public const int RewardEndTimeFieldNumber = 5;
    private ulong rewardEndTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong RewardEndTime {
      get { return rewardEndTime_; }
      set {
        rewardEndTime_ = value;
      }
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 6;
    private string config_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Config {
      get { return config_; }
      set {
        config_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "manual_end" field.</summary>
    public const int ManualEndFieldNumber = 7;
    private bool manualEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ManualEnd {
      get { return manualEnd_; }
      set {
        manualEnd_ = value;
      }
    }

    /// <summary>Field number for the "resource_path" field.</summary>
    public const int ResourcePathFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_resourcePath_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> resourcePath_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ResourcePath {
      get { return resourcePath_; }
    }

    /// <summary>Field number for the "activity_sub_type" field.</summary>
    public const int ActivitySubTypeFieldNumber = 9;
    private string activitySubType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivitySubType {
      get { return activitySubType_; }
      set {
        activitySubType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "activity_mode" field.</summary>
    public const int ActivityModeFieldNumber = 10;
    private global::DragonU3DSDK.Network.API.Protocol.ActivityMode activityMode_ = 0;
    /// <summary>
    /// 活动数据的模式
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.ActivityMode ActivityMode {
      get { return activityMode_; }
      set {
        activityMode_ = value;
      }
    }

    /// <summary>Field number for the "user_data" field.</summary>
    public const int UserDataFieldNumber = 11;
    private string userData_ = "";
    /// <summary>
    /// 部分项目所需要使用的用户数据上下文，默认为空字符串
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserData {
      get { return userData_; }
      set {
        userData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_test" field.</summary>
    public const int IsTestFieldNumber = 12;
    private bool isTest_;
    /// <summary>
    /// 是否为【白名单用户】提前重置了start_time的活动
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsTest {
      get { return isTest_; }
      set {
        isTest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResActivity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResActivity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActivityId != other.ActivityId) return false;
      if (ActivityType != other.ActivityType) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (RewardEndTime != other.RewardEndTime) return false;
      if (Config != other.Config) return false;
      if (ManualEnd != other.ManualEnd) return false;
      if(!resourcePath_.Equals(other.resourcePath_)) return false;
      if (ActivitySubType != other.ActivitySubType) return false;
      if (ActivityMode != other.ActivityMode) return false;
      if (UserData != other.UserData) return false;
      if (IsTest != other.IsTest) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActivityId.Length != 0) hash ^= ActivityId.GetHashCode();
      if (ActivityType.Length != 0) hash ^= ActivityType.GetHashCode();
      if (StartTime != 0UL) hash ^= StartTime.GetHashCode();
      if (EndTime != 0UL) hash ^= EndTime.GetHashCode();
      if (RewardEndTime != 0UL) hash ^= RewardEndTime.GetHashCode();
      if (Config.Length != 0) hash ^= Config.GetHashCode();
      if (ManualEnd != false) hash ^= ManualEnd.GetHashCode();
      hash ^= resourcePath_.GetHashCode();
      if (ActivitySubType.Length != 0) hash ^= ActivitySubType.GetHashCode();
      if (ActivityMode != 0) hash ^= ActivityMode.GetHashCode();
      if (UserData.Length != 0) hash ^= UserData.GetHashCode();
      if (IsTest != false) hash ^= IsTest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActivityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActivityId);
      }
      if (ActivityType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ActivityType);
      }
      if (StartTime != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(StartTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(EndTime);
      }
      if (RewardEndTime != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(RewardEndTime);
      }
      if (Config.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Config);
      }
      if (ManualEnd != false) {
        output.WriteRawTag(56);
        output.WriteBool(ManualEnd);
      }
      resourcePath_.WriteTo(output, _repeated_resourcePath_codec);
      if (ActivitySubType.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ActivitySubType);
      }
      if (ActivityMode != 0) {
        output.WriteRawTag(80);
        output.WriteEnum((int) ActivityMode);
      }
      if (UserData.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(UserData);
      }
      if (IsTest != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsTest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActivityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityId);
      }
      if (ActivityType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityType);
      }
      if (StartTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartTime);
      }
      if (EndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EndTime);
      }
      if (RewardEndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RewardEndTime);
      }
      if (Config.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Config);
      }
      if (ManualEnd != false) {
        size += 1 + 1;
      }
      size += resourcePath_.CalculateSize(_repeated_resourcePath_codec);
      if (ActivitySubType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivitySubType);
      }
      if (ActivityMode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActivityMode);
      }
      if (UserData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserData);
      }
      if (IsTest != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResActivity other) {
      if (other == null) {
        return;
      }
      if (other.ActivityId.Length != 0) {
        ActivityId = other.ActivityId;
      }
      if (other.ActivityType.Length != 0) {
        ActivityType = other.ActivityType;
      }
      if (other.StartTime != 0UL) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0UL) {
        EndTime = other.EndTime;
      }
      if (other.RewardEndTime != 0UL) {
        RewardEndTime = other.RewardEndTime;
      }
      if (other.Config.Length != 0) {
        Config = other.Config;
      }
      if (other.ManualEnd != false) {
        ManualEnd = other.ManualEnd;
      }
      resourcePath_.Add(other.resourcePath_);
      if (other.ActivitySubType.Length != 0) {
        ActivitySubType = other.ActivitySubType;
      }
      if (other.ActivityMode != 0) {
        ActivityMode = other.ActivityMode;
      }
      if (other.UserData.Length != 0) {
        UserData = other.UserData;
      }
      if (other.IsTest != false) {
        IsTest = other.IsTest;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ActivityId = input.ReadString();
            break;
          }
          case 18: {
            ActivityType = input.ReadString();
            break;
          }
          case 24: {
            StartTime = input.ReadUInt64();
            break;
          }
          case 32: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 40: {
            RewardEndTime = input.ReadUInt64();
            break;
          }
          case 50: {
            Config = input.ReadString();
            break;
          }
          case 56: {
            ManualEnd = input.ReadBool();
            break;
          }
          case 66: {
            resourcePath_.AddEntriesFrom(input, _repeated_resourcePath_codec);
            break;
          }
          case 74: {
            ActivitySubType = input.ReadString();
            break;
          }
          case 80: {
            ActivityMode = (global::DragonU3DSDK.Network.API.Protocol.ActivityMode) input.ReadEnum();
            break;
          }
          case 90: {
            UserData = input.ReadString();
            break;
          }
          case 96: {
            IsTest = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CGetActivities : pb::IMessage<CGetActivities> {
    private static readonly pb::MessageParser<CGetActivities> _parser = new pb::MessageParser<CGetActivities>(() => new CGetActivities());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CGetActivities> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetActivities() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetActivities(CGetActivities other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetActivities Clone() {
      return new CGetActivities(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CGetActivities);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CGetActivities other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CGetActivities other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class SGetActivities : pb::IMessage<SGetActivities> {
    private static readonly pb::MessageParser<SGetActivities> _parser = new pb::MessageParser<SGetActivities>(() => new SGetActivities());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SGetActivities> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetActivities() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetActivities(SGetActivities other) : this() {
      activities_ = other.activities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetActivities Clone() {
      return new SGetActivities(this);
    }

    /// <summary>Field number for the "activities" field.</summary>
    public const int ActivitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.Activity> _repeated_activities_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.Activity.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Activity> activities_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Activity>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Activity> Activities {
      get { return activities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SGetActivities);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SGetActivities other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!activities_.Equals(other.activities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= activities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      activities_.WriteTo(output, _repeated_activities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += activities_.CalculateSize(_repeated_activities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SGetActivities other) {
      if (other == null) {
        return;
      }
      activities_.Add(other.activities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            activities_.AddEntriesFrom(input, _repeated_activities_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CGetResActivities : pb::IMessage<CGetResActivities> {
    private static readonly pb::MessageParser<CGetResActivities> _parser = new pb::MessageParser<CGetResActivities>(() => new CGetResActivities());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CGetResActivities> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetResActivities() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetResActivities(CGetResActivities other) : this() {
      platform_ = other.platform_;
      version_ = other.version_;
      activityTypes_ = other.activityTypes_.Clone();
      advanceDays_ = other.advanceDays_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetResActivities Clone() {
      return new CGetResActivities(this);
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 1;
    private global::DragonU3DSDK.Network.API.Protocol.Platform platform_ = 0;
    /// <summary>
    /// 平台enum值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.Platform Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 2;
    private ulong version_;
    /// <summary>
    /// 已废弃 版本号 依赖 reqHeader:x-client-version-code 上传该字段
    /// </summary>
    [global::System.ObsoleteAttribute]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "activity_types" field.</summary>
    public const int ActivityTypesFieldNumber = 3;
    private static readonly pbc::MapField<string, string>.Codec _map_activityTypes_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 26);
    private readonly pbc::MapField<string, string> activityTypes_ = new pbc::MapField<string, string>();
    /// <summary>
    /// 非必传参数，某些项目的包内自定义活动模块(原有活动框架扩展，故需要使用map类型，用于客户端处理activity_id数值)，根据所传活动类型map, key为活动类型(例如OPS_EVENT_TYPE_XXX)，value为客户端生成的activity_id，下发对应活动类型的配置与资源文件名，无需时间数值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> ActivityTypes {
      get { return activityTypes_; }
    }

    /// <summary>Field number for the "advance_days" field.</summary>
    public const int AdvanceDaysFieldNumber = 4;
    private uint advanceDays_;
    /// <summary>
    /// 非必传参数，部分项目使用，指定下发几天后的待开始（包括正在进行中）的运营活动，并且不依据activityType去重；缺省值为0（仅提前1小时下发数据，并依据activityType去重）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint AdvanceDays {
      get { return advanceDays_; }
      set {
        advanceDays_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CGetResActivities);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CGetResActivities other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Platform != other.Platform) return false;
      if (Version != other.Version) return false;
      if (!ActivityTypes.Equals(other.ActivityTypes)) return false;
      if (AdvanceDays != other.AdvanceDays) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Platform != 0) hash ^= Platform.GetHashCode();
      if (Version != 0UL) hash ^= Version.GetHashCode();
      hash ^= ActivityTypes.GetHashCode();
      if (AdvanceDays != 0) hash ^= AdvanceDays.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Platform != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Platform);
      }
      if (Version != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Version);
      }
      activityTypes_.WriteTo(output, _map_activityTypes_codec);
      if (AdvanceDays != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AdvanceDays);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Platform != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Platform);
      }
      if (Version != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Version);
      }
      size += activityTypes_.CalculateSize(_map_activityTypes_codec);
      if (AdvanceDays != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AdvanceDays);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CGetResActivities other) {
      if (other == null) {
        return;
      }
      if (other.Platform != 0) {
        Platform = other.Platform;
      }
      if (other.Version != 0UL) {
        Version = other.Version;
      }
      activityTypes_.Add(other.activityTypes_);
      if (other.AdvanceDays != 0) {
        AdvanceDays = other.AdvanceDays;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Platform = (global::DragonU3DSDK.Network.API.Protocol.Platform) input.ReadEnum();
            break;
          }
          case 16: {
            Version = input.ReadUInt64();
            break;
          }
          case 26: {
            activityTypes_.AddEntriesFrom(input, _map_activityTypes_codec);
            break;
          }
          case 32: {
            AdvanceDays = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SGetResActivities : pb::IMessage<SGetResActivities> {
    private static readonly pb::MessageParser<SGetResActivities> _parser = new pb::MessageParser<SGetResActivities>(() => new SGetResActivities());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SGetResActivities> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetResActivities() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetResActivities(SGetResActivities other) : this() {
      activities_ = other.activities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetResActivities Clone() {
      return new SGetResActivities(this);
    }

    /// <summary>Field number for the "activities" field.</summary>
    public const int ActivitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.ResActivity> _repeated_activities_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.ResActivity.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ResActivity> activities_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ResActivity>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ResActivity> Activities {
      get { return activities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SGetResActivities);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SGetResActivities other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!activities_.Equals(other.activities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= activities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      activities_.WriteTo(output, _repeated_activities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += activities_.CalculateSize(_repeated_activities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SGetResActivities other) {
      if (other == null) {
        return;
      }
      activities_.Add(other.activities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            activities_.AddEntriesFrom(input, _repeated_activities_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取指定活动类型的活动的起止时间列表
  /// </summary>
  public sealed partial class ActivityTime : pb::IMessage<ActivityTime> {
    private static readonly pb::MessageParser<ActivityTime> _parser = new pb::MessageParser<ActivityTime>(() => new ActivityTime());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActivityTime> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActivityTime() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActivityTime(ActivityTime other) : this() {
      activityType_ = other.activityType_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      rewardEndTime_ = other.rewardEndTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActivityTime Clone() {
      return new ActivityTime(this);
    }

    /// <summary>Field number for the "activity_type" field.</summary>
    public const int ActivityTypeFieldNumber = 1;
    private string activityType_ = "";
    /// <summary>
    /// 活动类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActivityType {
      get { return activityType_; }
      set {
        activityType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 2;
    private long startTime_;
    /// <summary>
    /// 活动开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 3;
    private long endTime_;
    /// <summary>
    /// 活动结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "reward_end_time" field.</summary>
    public const int RewardEndTimeFieldNumber = 4;
    private long rewardEndTime_;
    /// <summary>
    /// 奖励展示结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RewardEndTime {
      get { return rewardEndTime_; }
      set {
        rewardEndTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActivityTime);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActivityTime other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActivityType != other.ActivityType) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (RewardEndTime != other.RewardEndTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActivityType.Length != 0) hash ^= ActivityType.GetHashCode();
      if (StartTime != 0L) hash ^= StartTime.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      if (RewardEndTime != 0L) hash ^= RewardEndTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActivityType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActivityType);
      }
      if (StartTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(StartTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(EndTime);
      }
      if (RewardEndTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RewardEndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActivityType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActivityType);
      }
      if (StartTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTime);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      if (RewardEndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RewardEndTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActivityTime other) {
      if (other == null) {
        return;
      }
      if (other.ActivityType.Length != 0) {
        ActivityType = other.ActivityType;
      }
      if (other.StartTime != 0L) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      if (other.RewardEndTime != 0L) {
        RewardEndTime = other.RewardEndTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ActivityType = input.ReadString();
            break;
          }
          case 16: {
            StartTime = input.ReadInt64();
            break;
          }
          case 24: {
            EndTime = input.ReadInt64();
            break;
          }
          case 32: {
            RewardEndTime = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CGetActivityTimes : pb::IMessage<CGetActivityTimes> {
    private static readonly pb::MessageParser<CGetActivityTimes> _parser = new pb::MessageParser<CGetActivityTimes>(() => new CGetActivityTimes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CGetActivityTimes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetActivityTimes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetActivityTimes(CGetActivityTimes other) : this() {
      activityTypes_ = other.activityTypes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetActivityTimes Clone() {
      return new CGetActivityTimes(this);
    }

    /// <summary>Field number for the "activity_types" field.</summary>
    public const int ActivityTypesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_activityTypes_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> activityTypes_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// 指定活动类型列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ActivityTypes {
      get { return activityTypes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CGetActivityTimes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CGetActivityTimes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!activityTypes_.Equals(other.activityTypes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= activityTypes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      activityTypes_.WriteTo(output, _repeated_activityTypes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += activityTypes_.CalculateSize(_repeated_activityTypes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CGetActivityTimes other) {
      if (other == null) {
        return;
      }
      activityTypes_.Add(other.activityTypes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            activityTypes_.AddEntriesFrom(input, _repeated_activityTypes_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SGetActivityTimes : pb::IMessage<SGetActivityTimes> {
    private static readonly pb::MessageParser<SGetActivityTimes> _parser = new pb::MessageParser<SGetActivityTimes>(() => new SGetActivityTimes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SGetActivityTimes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.ActivityReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetActivityTimes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetActivityTimes(SGetActivityTimes other) : this() {
      activities_ = other.activities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetActivityTimes Clone() {
      return new SGetActivityTimes(this);
    }

    /// <summary>Field number for the "activities" field.</summary>
    public const int ActivitiesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.ActivityTime> _repeated_activities_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.ActivityTime.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ActivityTime> activities_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ActivityTime>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.ActivityTime> Activities {
      get { return activities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SGetActivityTimes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SGetActivityTimes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!activities_.Equals(other.activities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= activities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      activities_.WriteTo(output, _repeated_activities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += activities_.CalculateSize(_repeated_activities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SGetActivityTimes other) {
      if (other == null) {
        return;
      }
      activities_.Add(other.activities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            activities_.AddEntriesFrom(input, _repeated_activities_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
