// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gift.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.Protocol {

  /// <summary>Holder for reflection information generated from gift.proto</summary>
  public static partial class GiftReflection {

    #region Descriptor
    /// <summary>File descriptor for gift.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GiftReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpnaWZ0LnByb3RvIgoKCEdpZnRJbmZvIrMBCgRHaWZ0Eg8KB2dpZnRfaWQY",
            "ASABKAkSGgoSc2VuZGVyX2ZhY2Vib29rX2lkGAMgASgJEhwKFHJlY2VpdmVy",
            "X2ZhY2Vib29rX2lkGAQgASgJEg4KBmV4cGlyZRgFIAEoBBIgCgtnaWZ0X3N0",
            "YXR1cxgGIAEoDjILLkdpZnRTdGF0dXMSHAoJZ2lmdF9pbmZvGAcgASgLMgku",
            "R2lmdEluZm8SEAoIaXNfdG9kYXkYCCABKAgiDAoKQ0xpc3RHaWZ0cyIiCgpT",
            "TGlzdEdpZnRzEhQKBWdpZnRzGAEgAygLMgUuR2lmdCJHCgpDU2VuZEdpZnRz",
            "EhsKE3RhcmdldF9mYWNlYm9va19pZHMYASADKAkSHAoJZ2lmdF9pbmZvGAIg",
            "ASgLMgkuR2lmdEluZm8iDAoKU1NlbmRHaWZ0cyIfCgtDQ2xhaW1HaWZ0cxIQ",
            "CghnaWZ0X2lkcxgBIAMoCSIfCgtTQ2xhaW1HaWZ0cxIQCghnaWZ0X2lkcxgB",
            "IAMoCSJGCglDQXNrR2lmdHMSGwoTdGFyZ2V0X2ZhY2Vib29rX2lkcxgBIAMo",
            "CRIcCglnaWZ0X2luZm8YAiABKAsyCS5HaWZ0SW5mbyILCglTQXNrR2lmdHMi",
            "HwoLQ1JlcGx5R2lmdHMSEAoIZ2lmdF9pZHMYASADKAkiHwoLU1JlcGx5R2lm",
            "dHMSEAoIZ2lmdF9pZHMYASADKAkqOgoKR2lmdFN0YXR1cxIICgRTRU5UEAAS",
            "CwoHQ0xBSU1FRBABEgkKBUFTS0VEEAISCgoGSEVMUEVEEANCVAojY29tLmRy",
            "YWdvbnBsdXMubmV0d29yay5hcGkucHJvdG9jb2xaCXByb3RvY29sc6oCIURy",
            "YWdvblUzRFNESy5OZXR3b3JrLkFQSS5Qcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DragonU3DSDK.Network.API.Protocol.GiftStatus), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.GiftInfo), global::DragonU3DSDK.Network.API.Protocol.GiftInfo.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.Gift), global::DragonU3DSDK.Network.API.Protocol.Gift.Parser, new[]{ "GiftId", "SenderFacebookId", "ReceiverFacebookId", "Expire", "GiftStatus", "GiftInfo", "IsToday" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CListGifts), global::DragonU3DSDK.Network.API.Protocol.CListGifts.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SListGifts), global::DragonU3DSDK.Network.API.Protocol.SListGifts.Parser, new[]{ "Gifts" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CSendGifts), global::DragonU3DSDK.Network.API.Protocol.CSendGifts.Parser, new[]{ "TargetFacebookIds", "GiftInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SSendGifts), global::DragonU3DSDK.Network.API.Protocol.SSendGifts.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CClaimGifts), global::DragonU3DSDK.Network.API.Protocol.CClaimGifts.Parser, new[]{ "GiftIds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SClaimGifts), global::DragonU3DSDK.Network.API.Protocol.SClaimGifts.Parser, new[]{ "GiftIds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CAskGifts), global::DragonU3DSDK.Network.API.Protocol.CAskGifts.Parser, new[]{ "TargetFacebookIds", "GiftInfo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SAskGifts), global::DragonU3DSDK.Network.API.Protocol.SAskGifts.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CReplyGifts), global::DragonU3DSDK.Network.API.Protocol.CReplyGifts.Parser, new[]{ "GiftIds" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SReplyGifts), global::DragonU3DSDK.Network.API.Protocol.SReplyGifts.Parser, new[]{ "GiftIds" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GiftStatus {
    [pbr::OriginalName("SENT")] Sent = 0,
    [pbr::OriginalName("CLAIMED")] Claimed = 1,
    [pbr::OriginalName("ASKED")] Asked = 2,
    [pbr::OriginalName("HELPED")] Helped = 3,
  }

  #endregion

  #region Messages
  public sealed partial class GiftInfo : pb::IMessage<GiftInfo> {
    private static readonly pb::MessageParser<GiftInfo> _parser = new pb::MessageParser<GiftInfo>(() => new GiftInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GiftInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GiftInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GiftInfo(GiftInfo other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GiftInfo Clone() {
      return new GiftInfo(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GiftInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GiftInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GiftInfo other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class Gift : pb::IMessage<Gift> {
    private static readonly pb::MessageParser<Gift> _parser = new pb::MessageParser<Gift>(() => new Gift());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Gift> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift(Gift other) : this() {
      giftId_ = other.giftId_;
      senderFacebookId_ = other.senderFacebookId_;
      receiverFacebookId_ = other.receiverFacebookId_;
      expire_ = other.expire_;
      giftStatus_ = other.giftStatus_;
      giftInfo_ = other.giftInfo_ != null ? other.giftInfo_.Clone() : null;
      isToday_ = other.isToday_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gift Clone() {
      return new Gift(this);
    }

    /// <summary>Field number for the "gift_id" field.</summary>
    public const int GiftIdFieldNumber = 1;
    private string giftId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GiftId {
      get { return giftId_; }
      set {
        giftId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sender_facebook_id" field.</summary>
    public const int SenderFacebookIdFieldNumber = 3;
    private string senderFacebookId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SenderFacebookId {
      get { return senderFacebookId_; }
      set {
        senderFacebookId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "receiver_facebook_id" field.</summary>
    public const int ReceiverFacebookIdFieldNumber = 4;
    private string receiverFacebookId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ReceiverFacebookId {
      get { return receiverFacebookId_; }
      set {
        receiverFacebookId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expire" field.</summary>
    public const int ExpireFieldNumber = 5;
    private ulong expire_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Expire {
      get { return expire_; }
      set {
        expire_ = value;
      }
    }

    /// <summary>Field number for the "gift_status" field.</summary>
    public const int GiftStatusFieldNumber = 6;
    private global::DragonU3DSDK.Network.API.Protocol.GiftStatus giftStatus_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.GiftStatus GiftStatus {
      get { return giftStatus_; }
      set {
        giftStatus_ = value;
      }
    }

    /// <summary>Field number for the "gift_info" field.</summary>
    public const int GiftInfoFieldNumber = 7;
    private global::DragonU3DSDK.Network.API.Protocol.GiftInfo giftInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.GiftInfo GiftInfo {
      get { return giftInfo_; }
      set {
        giftInfo_ = value;
      }
    }

    /// <summary>Field number for the "is_today" field.</summary>
    public const int IsTodayFieldNumber = 8;
    private bool isToday_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsToday {
      get { return isToday_; }
      set {
        isToday_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Gift);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Gift other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GiftId != other.GiftId) return false;
      if (SenderFacebookId != other.SenderFacebookId) return false;
      if (ReceiverFacebookId != other.ReceiverFacebookId) return false;
      if (Expire != other.Expire) return false;
      if (GiftStatus != other.GiftStatus) return false;
      if (!object.Equals(GiftInfo, other.GiftInfo)) return false;
      if (IsToday != other.IsToday) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GiftId.Length != 0) hash ^= GiftId.GetHashCode();
      if (SenderFacebookId.Length != 0) hash ^= SenderFacebookId.GetHashCode();
      if (ReceiverFacebookId.Length != 0) hash ^= ReceiverFacebookId.GetHashCode();
      if (Expire != 0UL) hash ^= Expire.GetHashCode();
      if (GiftStatus != 0) hash ^= GiftStatus.GetHashCode();
      if (giftInfo_ != null) hash ^= GiftInfo.GetHashCode();
      if (IsToday != false) hash ^= IsToday.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GiftId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GiftId);
      }
      if (SenderFacebookId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SenderFacebookId);
      }
      if (ReceiverFacebookId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ReceiverFacebookId);
      }
      if (Expire != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Expire);
      }
      if (GiftStatus != 0) {
        output.WriteRawTag(48);
        output.WriteEnum((int) GiftStatus);
      }
      if (giftInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GiftInfo);
      }
      if (IsToday != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsToday);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GiftId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GiftId);
      }
      if (SenderFacebookId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SenderFacebookId);
      }
      if (ReceiverFacebookId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReceiverFacebookId);
      }
      if (Expire != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Expire);
      }
      if (GiftStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GiftStatus);
      }
      if (giftInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GiftInfo);
      }
      if (IsToday != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Gift other) {
      if (other == null) {
        return;
      }
      if (other.GiftId.Length != 0) {
        GiftId = other.GiftId;
      }
      if (other.SenderFacebookId.Length != 0) {
        SenderFacebookId = other.SenderFacebookId;
      }
      if (other.ReceiverFacebookId.Length != 0) {
        ReceiverFacebookId = other.ReceiverFacebookId;
      }
      if (other.Expire != 0UL) {
        Expire = other.Expire;
      }
      if (other.GiftStatus != 0) {
        GiftStatus = other.GiftStatus;
      }
      if (other.giftInfo_ != null) {
        if (giftInfo_ == null) {
          GiftInfo = new global::DragonU3DSDK.Network.API.Protocol.GiftInfo();
        }
        GiftInfo.MergeFrom(other.GiftInfo);
      }
      if (other.IsToday != false) {
        IsToday = other.IsToday;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GiftId = input.ReadString();
            break;
          }
          case 26: {
            SenderFacebookId = input.ReadString();
            break;
          }
          case 34: {
            ReceiverFacebookId = input.ReadString();
            break;
          }
          case 40: {
            Expire = input.ReadUInt64();
            break;
          }
          case 48: {
            GiftStatus = (global::DragonU3DSDK.Network.API.Protocol.GiftStatus) input.ReadEnum();
            break;
          }
          case 58: {
            if (giftInfo_ == null) {
              GiftInfo = new global::DragonU3DSDK.Network.API.Protocol.GiftInfo();
            }
            input.ReadMessage(GiftInfo);
            break;
          }
          case 64: {
            IsToday = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CListGifts : pb::IMessage<CListGifts> {
    private static readonly pb::MessageParser<CListGifts> _parser = new pb::MessageParser<CListGifts>(() => new CListGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CListGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CListGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CListGifts(CListGifts other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CListGifts Clone() {
      return new CListGifts(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CListGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CListGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CListGifts other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class SListGifts : pb::IMessage<SListGifts> {
    private static readonly pb::MessageParser<SListGifts> _parser = new pb::MessageParser<SListGifts>(() => new SListGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SListGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SListGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SListGifts(SListGifts other) : this() {
      gifts_ = other.gifts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SListGifts Clone() {
      return new SListGifts(this);
    }

    /// <summary>Field number for the "gifts" field.</summary>
    public const int GiftsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.Gift> _repeated_gifts_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.Gift.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Gift> gifts_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Gift>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Gift> Gifts {
      get { return gifts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SListGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SListGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!gifts_.Equals(other.gifts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= gifts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      gifts_.WriteTo(output, _repeated_gifts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += gifts_.CalculateSize(_repeated_gifts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SListGifts other) {
      if (other == null) {
        return;
      }
      gifts_.Add(other.gifts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            gifts_.AddEntriesFrom(input, _repeated_gifts_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CSendGifts : pb::IMessage<CSendGifts> {
    private static readonly pb::MessageParser<CSendGifts> _parser = new pb::MessageParser<CSendGifts>(() => new CSendGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSendGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSendGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSendGifts(CSendGifts other) : this() {
      targetFacebookIds_ = other.targetFacebookIds_.Clone();
      giftInfo_ = other.giftInfo_ != null ? other.giftInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CSendGifts Clone() {
      return new CSendGifts(this);
    }

    /// <summary>Field number for the "target_facebook_ids" field.</summary>
    public const int TargetFacebookIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_targetFacebookIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> targetFacebookIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> TargetFacebookIds {
      get { return targetFacebookIds_; }
    }

    /// <summary>Field number for the "gift_info" field.</summary>
    public const int GiftInfoFieldNumber = 2;
    private global::DragonU3DSDK.Network.API.Protocol.GiftInfo giftInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.GiftInfo GiftInfo {
      get { return giftInfo_; }
      set {
        giftInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CSendGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CSendGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!targetFacebookIds_.Equals(other.targetFacebookIds_)) return false;
      if (!object.Equals(GiftInfo, other.GiftInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= targetFacebookIds_.GetHashCode();
      if (giftInfo_ != null) hash ^= GiftInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      targetFacebookIds_.WriteTo(output, _repeated_targetFacebookIds_codec);
      if (giftInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GiftInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += targetFacebookIds_.CalculateSize(_repeated_targetFacebookIds_codec);
      if (giftInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GiftInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CSendGifts other) {
      if (other == null) {
        return;
      }
      targetFacebookIds_.Add(other.targetFacebookIds_);
      if (other.giftInfo_ != null) {
        if (giftInfo_ == null) {
          GiftInfo = new global::DragonU3DSDK.Network.API.Protocol.GiftInfo();
        }
        GiftInfo.MergeFrom(other.GiftInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            targetFacebookIds_.AddEntriesFrom(input, _repeated_targetFacebookIds_codec);
            break;
          }
          case 18: {
            if (giftInfo_ == null) {
              GiftInfo = new global::DragonU3DSDK.Network.API.Protocol.GiftInfo();
            }
            input.ReadMessage(GiftInfo);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SSendGifts : pb::IMessage<SSendGifts> {
    private static readonly pb::MessageParser<SSendGifts> _parser = new pb::MessageParser<SSendGifts>(() => new SSendGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SSendGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSendGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSendGifts(SSendGifts other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SSendGifts Clone() {
      return new SSendGifts(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SSendGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SSendGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SSendGifts other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class CClaimGifts : pb::IMessage<CClaimGifts> {
    private static readonly pb::MessageParser<CClaimGifts> _parser = new pb::MessageParser<CClaimGifts>(() => new CClaimGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CClaimGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CClaimGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CClaimGifts(CClaimGifts other) : this() {
      giftIds_ = other.giftIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CClaimGifts Clone() {
      return new CClaimGifts(this);
    }

    /// <summary>Field number for the "gift_ids" field.</summary>
    public const int GiftIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_giftIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> giftIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GiftIds {
      get { return giftIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CClaimGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CClaimGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!giftIds_.Equals(other.giftIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= giftIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      giftIds_.WriteTo(output, _repeated_giftIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += giftIds_.CalculateSize(_repeated_giftIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CClaimGifts other) {
      if (other == null) {
        return;
      }
      giftIds_.Add(other.giftIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            giftIds_.AddEntriesFrom(input, _repeated_giftIds_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SClaimGifts : pb::IMessage<SClaimGifts> {
    private static readonly pb::MessageParser<SClaimGifts> _parser = new pb::MessageParser<SClaimGifts>(() => new SClaimGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SClaimGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SClaimGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SClaimGifts(SClaimGifts other) : this() {
      giftIds_ = other.giftIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SClaimGifts Clone() {
      return new SClaimGifts(this);
    }

    /// <summary>Field number for the "gift_ids" field.</summary>
    public const int GiftIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_giftIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> giftIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GiftIds {
      get { return giftIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SClaimGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SClaimGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!giftIds_.Equals(other.giftIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= giftIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      giftIds_.WriteTo(output, _repeated_giftIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += giftIds_.CalculateSize(_repeated_giftIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SClaimGifts other) {
      if (other == null) {
        return;
      }
      giftIds_.Add(other.giftIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            giftIds_.AddEntriesFrom(input, _repeated_giftIds_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CAskGifts : pb::IMessage<CAskGifts> {
    private static readonly pb::MessageParser<CAskGifts> _parser = new pb::MessageParser<CAskGifts>(() => new CAskGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CAskGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAskGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAskGifts(CAskGifts other) : this() {
      targetFacebookIds_ = other.targetFacebookIds_.Clone();
      giftInfo_ = other.giftInfo_ != null ? other.giftInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAskGifts Clone() {
      return new CAskGifts(this);
    }

    /// <summary>Field number for the "target_facebook_ids" field.</summary>
    public const int TargetFacebookIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_targetFacebookIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> targetFacebookIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> TargetFacebookIds {
      get { return targetFacebookIds_; }
    }

    /// <summary>Field number for the "gift_info" field.</summary>
    public const int GiftInfoFieldNumber = 2;
    private global::DragonU3DSDK.Network.API.Protocol.GiftInfo giftInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.GiftInfo GiftInfo {
      get { return giftInfo_; }
      set {
        giftInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CAskGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CAskGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!targetFacebookIds_.Equals(other.targetFacebookIds_)) return false;
      if (!object.Equals(GiftInfo, other.GiftInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= targetFacebookIds_.GetHashCode();
      if (giftInfo_ != null) hash ^= GiftInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      targetFacebookIds_.WriteTo(output, _repeated_targetFacebookIds_codec);
      if (giftInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GiftInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += targetFacebookIds_.CalculateSize(_repeated_targetFacebookIds_codec);
      if (giftInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GiftInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CAskGifts other) {
      if (other == null) {
        return;
      }
      targetFacebookIds_.Add(other.targetFacebookIds_);
      if (other.giftInfo_ != null) {
        if (giftInfo_ == null) {
          GiftInfo = new global::DragonU3DSDK.Network.API.Protocol.GiftInfo();
        }
        GiftInfo.MergeFrom(other.GiftInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            targetFacebookIds_.AddEntriesFrom(input, _repeated_targetFacebookIds_codec);
            break;
          }
          case 18: {
            if (giftInfo_ == null) {
              GiftInfo = new global::DragonU3DSDK.Network.API.Protocol.GiftInfo();
            }
            input.ReadMessage(GiftInfo);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SAskGifts : pb::IMessage<SAskGifts> {
    private static readonly pb::MessageParser<SAskGifts> _parser = new pb::MessageParser<SAskGifts>(() => new SAskGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SAskGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SAskGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SAskGifts(SAskGifts other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SAskGifts Clone() {
      return new SAskGifts(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SAskGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SAskGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SAskGifts other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class CReplyGifts : pb::IMessage<CReplyGifts> {
    private static readonly pb::MessageParser<CReplyGifts> _parser = new pb::MessageParser<CReplyGifts>(() => new CReplyGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CReplyGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CReplyGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CReplyGifts(CReplyGifts other) : this() {
      giftIds_ = other.giftIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CReplyGifts Clone() {
      return new CReplyGifts(this);
    }

    /// <summary>Field number for the "gift_ids" field.</summary>
    public const int GiftIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_giftIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> giftIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GiftIds {
      get { return giftIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CReplyGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CReplyGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!giftIds_.Equals(other.giftIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= giftIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      giftIds_.WriteTo(output, _repeated_giftIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += giftIds_.CalculateSize(_repeated_giftIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CReplyGifts other) {
      if (other == null) {
        return;
      }
      giftIds_.Add(other.giftIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            giftIds_.AddEntriesFrom(input, _repeated_giftIds_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SReplyGifts : pb::IMessage<SReplyGifts> {
    private static readonly pb::MessageParser<SReplyGifts> _parser = new pb::MessageParser<SReplyGifts>(() => new SReplyGifts());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SReplyGifts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.GiftReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SReplyGifts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SReplyGifts(SReplyGifts other) : this() {
      giftIds_ = other.giftIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SReplyGifts Clone() {
      return new SReplyGifts(this);
    }

    /// <summary>Field number for the "gift_ids" field.</summary>
    public const int GiftIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_giftIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> giftIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> GiftIds {
      get { return giftIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SReplyGifts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SReplyGifts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!giftIds_.Equals(other.giftIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= giftIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      giftIds_.WriteTo(output, _repeated_giftIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += giftIds_.CalculateSize(_repeated_giftIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SReplyGifts other) {
      if (other == null) {
        return;
      }
      giftIds_.Add(other.giftIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            giftIds_.AddEntriesFrom(input, _repeated_giftIds_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
