// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: others.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.Protocol {

  /// <summary>Holder for reflection information generated from others.proto</summary>
  public static partial class OthersReflection {

    #region Descriptor
    /// <summary>File descriptor for others.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OthersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxvdGhlcnMucHJvdG8aDGNvbW1vbi5wcm90byIMCgpDSGVhcnRCZWF0Ih8K",
            "ClNIZWFydEJlYXQSEQoJdGltZXN0YW1wGAEgASgEIhsKCkNHZXRDb25maWcS",
            "DQoFcm91dGUYASABKAkiKwoKU0dldENvbmZpZxIdCgZjb25maWcYCCABKAsy",
            "DS5DbGllbnRDb25maWcixQQKDEFubm91bmNlbWVudBIXCg9hbm5vdW5jZW1l",
            "bnRfaWQYASABKAkSEgoKc3RhcnRfdGltZRgCIAEoBBIQCghlbmRfdGltZRgD",
            "IAEoBBISCgpjZF9zZWNvbmRzGAQgASgEEg4KBmlzX2FsbBgFIAEoCBIYChBw",
            "bGF5ZXJfY29uZGl0aW9uGAYgASgJEg8KB2ltZ191cmwYByABKAkSJwoIbXNn",
            "X3R5cGUYCCABKA4yFS5Bbm5vdW5jZW1lbnQuTXNnVHlwZRIQCghtc2dfdGV4",
            "dBgJIAEoCRI7ChBsb2NhbGVfbXNnX2luZm9zGAogAygLMiEuQW5ub3VuY2Vt",
            "ZW50LkxvY2FsZU1zZ0luZm9zRW50cnkSEgoKbWFudWFsX2VuZBgLIAEoCBIR",
            "Cgltc2dfdGl0bGUYDCABKAkSPQoRbG9jYWxlX21zZ190aXRsZXMYDSADKAsy",
            "Ii5Bbm5vdW5jZW1lbnQuTG9jYWxlTXNnVGl0bGVzRW50cnkSDAoEbGluaxgO",
            "IAEoCRo1ChNMb2NhbGVNc2dJbmZvc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2",
            "YWx1ZRgCIAEoCToCOAEaNgoUTG9jYWxlTXNnVGl0bGVzRW50cnkSCwoDa2V5",
            "GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJMCgdNc2dUeXBlEg0KCUNVU1RP",
            "TUlaRRAAEhIKDk5FV19SRVNUQVVSQU5UEAESDQoJTkVXX0VWRU5UEAISDwoL",
            "TkVXX0ZFQVRVUkUQAyIUChJDTGlzdEFubm91bmNlbWVudHMiOQoSU0xpc3RB",
            "bm5vdW5jZW1lbnRzEiMKDGFubm91bmNlbWVudBgBIAMoCzINLkFubm91bmNl",
            "bWVudEJUCiNjb20uZHJhZ29ucGx1cy5uZXR3b3JrLmFwaS5wcm90b2NvbFoJ",
            "cHJvdG9jb2xzqgIhRHJhZ29uVTNEU0RLLk5ldHdvcmsuQVBJLlByb3RvY29s",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DragonU3DSDK.Network.API.Protocol.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CHeartBeat), global::DragonU3DSDK.Network.API.Protocol.CHeartBeat.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SHeartBeat), global::DragonU3DSDK.Network.API.Protocol.SHeartBeat.Parser, new[]{ "Timestamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CGetConfig), global::DragonU3DSDK.Network.API.Protocol.CGetConfig.Parser, new[]{ "Route" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SGetConfig), global::DragonU3DSDK.Network.API.Protocol.SGetConfig.Parser, new[]{ "Config" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.Announcement), global::DragonU3DSDK.Network.API.Protocol.Announcement.Parser, new[]{ "AnnouncementId", "StartTime", "EndTime", "CdSeconds", "IsAll", "PlayerCondition", "ImgUrl", "MsgType", "MsgText", "LocaleMsgInfos", "ManualEnd", "MsgTitle", "LocaleMsgTitles", "Link" }, null, new[]{ typeof(global::DragonU3DSDK.Network.API.Protocol.Announcement.Types.MsgType) }, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CListAnnouncements), global::DragonU3DSDK.Network.API.Protocol.CListAnnouncements.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SListAnnouncements), global::DragonU3DSDK.Network.API.Protocol.SListAnnouncements.Parser, new[]{ "Announcement" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CHeartBeat : pb::IMessage<CHeartBeat> {
    private static readonly pb::MessageParser<CHeartBeat> _parser = new pb::MessageParser<CHeartBeat>(() => new CHeartBeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CHeartBeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CHeartBeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CHeartBeat(CHeartBeat other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CHeartBeat Clone() {
      return new CHeartBeat(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CHeartBeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CHeartBeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CHeartBeat other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class SHeartBeat : pb::IMessage<SHeartBeat> {
    private static readonly pb::MessageParser<SHeartBeat> _parser = new pb::MessageParser<SHeartBeat>(() => new SHeartBeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SHeartBeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SHeartBeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SHeartBeat(SHeartBeat other) : this() {
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SHeartBeat Clone() {
      return new SHeartBeat(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private ulong timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SHeartBeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SHeartBeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0UL) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SHeartBeat other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0UL) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CGetConfig : pb::IMessage<CGetConfig> {
    private static readonly pb::MessageParser<CGetConfig> _parser = new pb::MessageParser<CGetConfig>(() => new CGetConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CGetConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetConfig(CGetConfig other) : this() {
      route_ = other.route_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetConfig Clone() {
      return new CGetConfig(this);
    }

    /// <summary>Field number for the "route" field.</summary>
    public const int RouteFieldNumber = 1;
    private string route_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Route {
      get { return route_; }
      set {
        route_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CGetConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CGetConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Route != other.Route) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Route.Length != 0) hash ^= Route.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Route.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Route);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Route.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Route);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CGetConfig other) {
      if (other == null) {
        return;
      }
      if (other.Route.Length != 0) {
        Route = other.Route;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Route = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SGetConfig : pb::IMessage<SGetConfig> {
    private static readonly pb::MessageParser<SGetConfig> _parser = new pb::MessageParser<SGetConfig>(() => new SGetConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SGetConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetConfig(SGetConfig other) : this() {
      config_ = other.config_ != null ? other.config_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetConfig Clone() {
      return new SGetConfig(this);
    }

    /// <summary>Field number for the "config" field.</summary>
    public const int ConfigFieldNumber = 8;
    private global::DragonU3DSDK.Network.API.Protocol.ClientConfig config_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.ClientConfig Config {
      get { return config_; }
      set {
        config_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SGetConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SGetConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Config, other.Config)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (config_ != null) hash ^= Config.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (config_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Config);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (config_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Config);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SGetConfig other) {
      if (other == null) {
        return;
      }
      if (other.config_ != null) {
        if (config_ == null) {
          Config = new global::DragonU3DSDK.Network.API.Protocol.ClientConfig();
        }
        Config.MergeFrom(other.Config);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 66: {
            if (config_ == null) {
              Config = new global::DragonU3DSDK.Network.API.Protocol.ClientConfig();
            }
            input.ReadMessage(Config);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///公告
  /// </summary>
  public sealed partial class Announcement : pb::IMessage<Announcement> {
    private static readonly pb::MessageParser<Announcement> _parser = new pb::MessageParser<Announcement>(() => new Announcement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Announcement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Announcement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Announcement(Announcement other) : this() {
      announcementId_ = other.announcementId_;
      startTime_ = other.startTime_;
      endTime_ = other.endTime_;
      cdSeconds_ = other.cdSeconds_;
      isAll_ = other.isAll_;
      playerCondition_ = other.playerCondition_;
      imgUrl_ = other.imgUrl_;
      msgType_ = other.msgType_;
      msgText_ = other.msgText_;
      localeMsgInfos_ = other.localeMsgInfos_.Clone();
      manualEnd_ = other.manualEnd_;
      msgTitle_ = other.msgTitle_;
      localeMsgTitles_ = other.localeMsgTitles_.Clone();
      link_ = other.link_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Announcement Clone() {
      return new Announcement(this);
    }

    /// <summary>Field number for the "announcement_id" field.</summary>
    public const int AnnouncementIdFieldNumber = 1;
    private string announcementId_ = "";
    /// <summary>
    ///公告id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnnouncementId {
      get { return announcementId_; }
      set {
        announcementId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 2;
    private ulong startTime_;
    /// <summary>
    ///公告开始时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 3;
    private ulong endTime_;
    /// <summary>
    ///公告结束时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "cd_seconds" field.</summary>
    public const int CdSecondsFieldNumber = 4;
    private ulong cdSeconds_;
    /// <summary>
    ///公告弹出间隔时间（单位：秒）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong CdSeconds {
      get { return cdSeconds_; }
      set {
        cdSeconds_ = value;
      }
    }

    /// <summary>Field number for the "is_all" field.</summary>
    public const int IsAllFieldNumber = 5;
    private bool isAll_;
    /// <summary>
    ///是否发送全体玩家
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAll {
      get { return isAll_; }
      set {
        isAll_ = value;
      }
    }

    /// <summary>Field number for the "player_condition" field.</summary>
    public const int PlayerConditionFieldNumber = 6;
    private string playerCondition_ = "";
    /// <summary>
    ///玩家条件筛选
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlayerCondition {
      get { return playerCondition_; }
      set {
        playerCondition_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "img_url" field.</summary>
    public const int ImgUrlFieldNumber = 7;
    private string imgUrl_ = "";
    /// <summary>
    ///公告图片链接
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImgUrl {
      get { return imgUrl_; }
      set {
        imgUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg_type" field.</summary>
    public const int MsgTypeFieldNumber = 8;
    private global::DragonU3DSDK.Network.API.Protocol.Announcement.Types.MsgType msgType_ = 0;
    /// <summary>
    ///公告信息类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DragonU3DSDK.Network.API.Protocol.Announcement.Types.MsgType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "msg_text" field.</summary>
    public const int MsgTextFieldNumber = 9;
    private string msgText_ = "";
    /// <summary>
    ///公告信息内容（若自定义类型）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MsgText {
      get { return msgText_; }
      set {
        msgText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locale_msg_infos" field.</summary>
    public const int LocaleMsgInfosFieldNumber = 10;
    private static readonly pbc::MapField<string, string>.Codec _map_localeMsgInfos_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 82);
    private readonly pbc::MapField<string, string> localeMsgInfos_ = new pbc::MapField<string, string>();
    /// <summary>
    ///公告信息内容多语言（若自定义类型)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> LocaleMsgInfos {
      get { return localeMsgInfos_; }
    }

    /// <summary>Field number for the "manual_end" field.</summary>
    public const int ManualEndFieldNumber = 11;
    private bool manualEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ManualEnd {
      get { return manualEnd_; }
      set {
        manualEnd_ = value;
      }
    }

    /// <summary>Field number for the "msg_title" field.</summary>
    public const int MsgTitleFieldNumber = 12;
    private string msgTitle_ = "";
    /// <summary>
    /// 公告信息标题（若自定义类型，非必填）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MsgTitle {
      get { return msgTitle_; }
      set {
        msgTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locale_msg_titles" field.</summary>
    public const int LocaleMsgTitlesFieldNumber = 13;
    private static readonly pbc::MapField<string, string>.Codec _map_localeMsgTitles_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 106);
    private readonly pbc::MapField<string, string> localeMsgTitles_ = new pbc::MapField<string, string>();
    /// <summary>
    ///公告信息标题多语言（若自定义类型，非必填)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> LocaleMsgTitles {
      get { return localeMsgTitles_; }
    }

    /// <summary>Field number for the "link" field.</summary>
    public const int LinkFieldNumber = 14;
    private string link_ = "";
    /// <summary>
    /// 跳转链接（非必填）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Link {
      get { return link_; }
      set {
        link_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Announcement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Announcement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AnnouncementId != other.AnnouncementId) return false;
      if (StartTime != other.StartTime) return false;
      if (EndTime != other.EndTime) return false;
      if (CdSeconds != other.CdSeconds) return false;
      if (IsAll != other.IsAll) return false;
      if (PlayerCondition != other.PlayerCondition) return false;
      if (ImgUrl != other.ImgUrl) return false;
      if (MsgType != other.MsgType) return false;
      if (MsgText != other.MsgText) return false;
      if (!LocaleMsgInfos.Equals(other.LocaleMsgInfos)) return false;
      if (ManualEnd != other.ManualEnd) return false;
      if (MsgTitle != other.MsgTitle) return false;
      if (!LocaleMsgTitles.Equals(other.LocaleMsgTitles)) return false;
      if (Link != other.Link) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AnnouncementId.Length != 0) hash ^= AnnouncementId.GetHashCode();
      if (StartTime != 0UL) hash ^= StartTime.GetHashCode();
      if (EndTime != 0UL) hash ^= EndTime.GetHashCode();
      if (CdSeconds != 0UL) hash ^= CdSeconds.GetHashCode();
      if (IsAll != false) hash ^= IsAll.GetHashCode();
      if (PlayerCondition.Length != 0) hash ^= PlayerCondition.GetHashCode();
      if (ImgUrl.Length != 0) hash ^= ImgUrl.GetHashCode();
      if (MsgType != 0) hash ^= MsgType.GetHashCode();
      if (MsgText.Length != 0) hash ^= MsgText.GetHashCode();
      hash ^= LocaleMsgInfos.GetHashCode();
      if (ManualEnd != false) hash ^= ManualEnd.GetHashCode();
      if (MsgTitle.Length != 0) hash ^= MsgTitle.GetHashCode();
      hash ^= LocaleMsgTitles.GetHashCode();
      if (Link.Length != 0) hash ^= Link.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AnnouncementId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AnnouncementId);
      }
      if (StartTime != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(StartTime);
      }
      if (EndTime != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(EndTime);
      }
      if (CdSeconds != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(CdSeconds);
      }
      if (IsAll != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsAll);
      }
      if (PlayerCondition.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PlayerCondition);
      }
      if (ImgUrl.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ImgUrl);
      }
      if (MsgType != 0) {
        output.WriteRawTag(64);
        output.WriteEnum((int) MsgType);
      }
      if (MsgText.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(MsgText);
      }
      localeMsgInfos_.WriteTo(output, _map_localeMsgInfos_codec);
      if (ManualEnd != false) {
        output.WriteRawTag(88);
        output.WriteBool(ManualEnd);
      }
      if (MsgTitle.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(MsgTitle);
      }
      localeMsgTitles_.WriteTo(output, _map_localeMsgTitles_codec);
      if (Link.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Link);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AnnouncementId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnnouncementId);
      }
      if (StartTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(StartTime);
      }
      if (EndTime != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EndTime);
      }
      if (CdSeconds != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CdSeconds);
      }
      if (IsAll != false) {
        size += 1 + 1;
      }
      if (PlayerCondition.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerCondition);
      }
      if (ImgUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImgUrl);
      }
      if (MsgType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (MsgText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MsgText);
      }
      size += localeMsgInfos_.CalculateSize(_map_localeMsgInfos_codec);
      if (ManualEnd != false) {
        size += 1 + 1;
      }
      if (MsgTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MsgTitle);
      }
      size += localeMsgTitles_.CalculateSize(_map_localeMsgTitles_codec);
      if (Link.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Link);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Announcement other) {
      if (other == null) {
        return;
      }
      if (other.AnnouncementId.Length != 0) {
        AnnouncementId = other.AnnouncementId;
      }
      if (other.StartTime != 0UL) {
        StartTime = other.StartTime;
      }
      if (other.EndTime != 0UL) {
        EndTime = other.EndTime;
      }
      if (other.CdSeconds != 0UL) {
        CdSeconds = other.CdSeconds;
      }
      if (other.IsAll != false) {
        IsAll = other.IsAll;
      }
      if (other.PlayerCondition.Length != 0) {
        PlayerCondition = other.PlayerCondition;
      }
      if (other.ImgUrl.Length != 0) {
        ImgUrl = other.ImgUrl;
      }
      if (other.MsgType != 0) {
        MsgType = other.MsgType;
      }
      if (other.MsgText.Length != 0) {
        MsgText = other.MsgText;
      }
      localeMsgInfos_.Add(other.localeMsgInfos_);
      if (other.ManualEnd != false) {
        ManualEnd = other.ManualEnd;
      }
      if (other.MsgTitle.Length != 0) {
        MsgTitle = other.MsgTitle;
      }
      localeMsgTitles_.Add(other.localeMsgTitles_);
      if (other.Link.Length != 0) {
        Link = other.Link;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AnnouncementId = input.ReadString();
            break;
          }
          case 16: {
            StartTime = input.ReadUInt64();
            break;
          }
          case 24: {
            EndTime = input.ReadUInt64();
            break;
          }
          case 32: {
            CdSeconds = input.ReadUInt64();
            break;
          }
          case 40: {
            IsAll = input.ReadBool();
            break;
          }
          case 50: {
            PlayerCondition = input.ReadString();
            break;
          }
          case 58: {
            ImgUrl = input.ReadString();
            break;
          }
          case 64: {
            MsgType = (global::DragonU3DSDK.Network.API.Protocol.Announcement.Types.MsgType) input.ReadEnum();
            break;
          }
          case 74: {
            MsgText = input.ReadString();
            break;
          }
          case 82: {
            localeMsgInfos_.AddEntriesFrom(input, _map_localeMsgInfos_codec);
            break;
          }
          case 88: {
            ManualEnd = input.ReadBool();
            break;
          }
          case 98: {
            MsgTitle = input.ReadString();
            break;
          }
          case 106: {
            localeMsgTitles_.AddEntriesFrom(input, _map_localeMsgTitles_codec);
            break;
          }
          case 114: {
            Link = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Announcement message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MsgType {
        /// <summary>
        ///自定义
        /// </summary>
        [pbr::OriginalName("CUSTOMIZE")] Customize = 0,
        /// <summary>
        ///新餐厅
        /// </summary>
        [pbr::OriginalName("NEW_RESTAURANT")] NewRestaurant = 1,
        /// <summary>
        ///新活动
        /// </summary>
        [pbr::OriginalName("NEW_EVENT")] NewEvent = 2,
        /// <summary>
        ///新功能
        /// </summary>
        [pbr::OriginalName("NEW_FEATURE")] NewFeature = 3,
      }

    }
    #endregion

  }

  public sealed partial class CListAnnouncements : pb::IMessage<CListAnnouncements> {
    private static readonly pb::MessageParser<CListAnnouncements> _parser = new pb::MessageParser<CListAnnouncements>(() => new CListAnnouncements());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CListAnnouncements> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CListAnnouncements() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CListAnnouncements(CListAnnouncements other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CListAnnouncements Clone() {
      return new CListAnnouncements(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CListAnnouncements);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CListAnnouncements other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CListAnnouncements other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class SListAnnouncements : pb::IMessage<SListAnnouncements> {
    private static readonly pb::MessageParser<SListAnnouncements> _parser = new pb::MessageParser<SListAnnouncements>(() => new SListAnnouncements());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SListAnnouncements> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.OthersReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SListAnnouncements() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SListAnnouncements(SListAnnouncements other) : this() {
      announcement_ = other.announcement_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SListAnnouncements Clone() {
      return new SListAnnouncements(this);
    }

    /// <summary>Field number for the "announcement" field.</summary>
    public const int AnnouncementFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.Protocol.Announcement> _repeated_announcement_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.Protocol.Announcement.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Announcement> announcement_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Announcement>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.Protocol.Announcement> Announcement {
      get { return announcement_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SListAnnouncements);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SListAnnouncements other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!announcement_.Equals(other.announcement_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= announcement_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      announcement_.WriteTo(output, _repeated_announcement_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += announcement_.CalculateSize(_repeated_announcement_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SListAnnouncements other) {
      if (other == null) {
        return;
      }
      announcement_.Add(other.announcement_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            announcement_.AddEntriesFrom(input, _repeated_announcement_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
