// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: remote_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.Protocol {

  /// <summary>Holder for reflection information generated from remote_config.proto</summary>
  public static partial class RemoteConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for remote_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RemoteConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNyZW1vdGVfY29uZmlnLnByb3RvIkEKEUNvbmZpZ1ZlcnNpb25Db2RlEhcK",
            "D2FuZHJvaWRfdmVyc2lvbhgBIAEoDRITCgtpb3NfdmVyc2lvbhgCIAEoDSLC",
            "AQoWQ0dldFNlZ21lbnRhdGlvbkNvbmZpZxISCgpjb25maWdfa2V5GAEgAygJ",
            "EkMKD2NvbmZpZ19ncm91cF9pZBgCIAMoCzIqLkNHZXRTZWdtZW50YXRpb25D",
            "b25maWcuQ29uZmlnR3JvdXBJZEVudHJ5EhkKEW9ubHlfZ3JvdXBfY29uZmln",
            "GAMgASgIGjQKEkNvbmZpZ0dyb3VwSWRFbnRyeRILCgNrZXkYASABKAkSDQoF",
            "dmFsdWUYAiABKA06AjgBIqIDChZTR2V0U2VnbWVudGF0aW9uQ29uZmlnEjwK",
            "C2NvbmZpZ19kYXRhGAEgAygLMicuU0dldFNlZ21lbnRhdGlvbkNvbmZpZy5D",
            "b25maWdEYXRhRW50cnkSPwoNZ3JvdXBfaWRfZGF0YRgCIAMoCzIoLlNHZXRT",
            "ZWdtZW50YXRpb25Db25maWcuR3JvdXBJZERhdGFFbnRyeRI+Cgx2ZXJzaW9u",
            "X2NvZGUYAyADKAsyKC5TR2V0U2VnbWVudGF0aW9uQ29uZmlnLlZlcnNpb25D",
            "b2RlRW50cnkSGgoSY2FtcGFpZ25fdHlwZV9jb2RlGAQgASgFGjEKD0NvbmZp",
            "Z0RhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGjIK",
            "EEdyb3VwSWREYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgN",
            "OgI4ARpGChBWZXJzaW9uQ29kZUVudHJ5EgsKA2tleRgBIAEoCRIhCgV2YWx1",
            "ZRgCIAEoCzISLkNvbmZpZ1ZlcnNpb25Db2RlOgI4AUJUCiNjb20uZHJhZ29u",
            "cGx1cy5uZXR3b3JrLmFwaS5wcm90b2NvbFoJcHJvdG9jb2xzqgIhRHJhZ29u",
            "VTNEU0RLLk5ldHdvcmsuQVBJLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode), global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode.Parser, new[]{ "AndroidVersion", "IosVersion" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.CGetSegmentationConfig), global::DragonU3DSDK.Network.API.Protocol.CGetSegmentationConfig.Parser, new[]{ "ConfigKey", "ConfigGroupId", "OnlyGroupConfig" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::DragonU3DSDK.Network.API.Protocol.SGetSegmentationConfig), global::DragonU3DSDK.Network.API.Protocol.SGetSegmentationConfig.Parser, new[]{ "ConfigData", "GroupIdData", "VersionCode", "CampaignTypeCode" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 配置最小支持版本信息
  /// </summary>
  public sealed partial class ConfigVersionCode : pb::IMessage<ConfigVersionCode> {
    private static readonly pb::MessageParser<ConfigVersionCode> _parser = new pb::MessageParser<ConfigVersionCode>(() => new ConfigVersionCode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigVersionCode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.RemoteConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigVersionCode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigVersionCode(ConfigVersionCode other) : this() {
      androidVersion_ = other.androidVersion_;
      iosVersion_ = other.iosVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigVersionCode Clone() {
      return new ConfigVersionCode(this);
    }

    /// <summary>Field number for the "android_version" field.</summary>
    public const int AndroidVersionFieldNumber = 1;
    private uint androidVersion_;
    /// <summary>
    /// 安卓版本build号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint AndroidVersion {
      get { return androidVersion_; }
      set {
        androidVersion_ = value;
      }
    }

    /// <summary>Field number for the "ios_version" field.</summary>
    public const int IosVersionFieldNumber = 2;
    private uint iosVersion_;
    /// <summary>
    /// iOS版本build号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IosVersion {
      get { return iosVersion_; }
      set {
        iosVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigVersionCode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigVersionCode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AndroidVersion != other.AndroidVersion) return false;
      if (IosVersion != other.IosVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AndroidVersion != 0) hash ^= AndroidVersion.GetHashCode();
      if (IosVersion != 0) hash ^= IosVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AndroidVersion != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(AndroidVersion);
      }
      if (IosVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(IosVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AndroidVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AndroidVersion);
      }
      if (IosVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IosVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigVersionCode other) {
      if (other == null) {
        return;
      }
      if (other.AndroidVersion != 0) {
        AndroidVersion = other.AndroidVersion;
      }
      if (other.IosVersion != 0) {
        IosVersion = other.IosVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AndroidVersion = input.ReadUInt32();
            break;
          }
          case 16: {
            IosVersion = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取远端配置 之 分层配置（仅使用功能标识名获取）
  /// </summary>
  public sealed partial class CGetSegmentationConfig : pb::IMessage<CGetSegmentationConfig> {
    private static readonly pb::MessageParser<CGetSegmentationConfig> _parser = new pb::MessageParser<CGetSegmentationConfig>(() => new CGetSegmentationConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CGetSegmentationConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.RemoteConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetSegmentationConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetSegmentationConfig(CGetSegmentationConfig other) : this() {
      configKey_ = other.configKey_.Clone();
      configGroupId_ = other.configGroupId_.Clone();
      onlyGroupConfig_ = other.onlyGroupConfig_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CGetSegmentationConfig Clone() {
      return new CGetSegmentationConfig(this);
    }

    /// <summary>Field number for the "config_key" field.</summary>
    public const int ConfigKeyFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_configKey_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> configKey_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// 指定功能标识键名(list，支持多个)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ConfigKey {
      get { return configKey_; }
    }

    /// <summary>Field number for the "config_group_id" field.</summary>
    public const int ConfigGroupIdFieldNumber = 2;
    private static readonly pbc::MapField<string, uint>.Codec _map_configGroupId_codec
        = new pbc::MapField<string, uint>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForUInt32(16), 18);
    private readonly pbc::MapField<string, uint> configGroupId_ = new pbc::MapField<string, uint>();
    /// <summary>
    /// 指定功能标识键名对应group id （获取指定group id的配置数据，若此字段有值，则忽略config key请求字段）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, uint> ConfigGroupId {
      get { return configGroupId_; }
    }

    /// <summary>Field number for the "only_group_config" field.</summary>
    public const int OnlyGroupConfigFieldNumber = 3;
    private bool onlyGroupConfig_;
    /// <summary>
    /// 若传true，仅下发与rules表内groupId关联的配置数据表内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool OnlyGroupConfig {
      get { return onlyGroupConfig_; }
      set {
        onlyGroupConfig_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CGetSegmentationConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CGetSegmentationConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!configKey_.Equals(other.configKey_)) return false;
      if (!ConfigGroupId.Equals(other.ConfigGroupId)) return false;
      if (OnlyGroupConfig != other.OnlyGroupConfig) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= configKey_.GetHashCode();
      hash ^= ConfigGroupId.GetHashCode();
      if (OnlyGroupConfig != false) hash ^= OnlyGroupConfig.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      configKey_.WriteTo(output, _repeated_configKey_codec);
      configGroupId_.WriteTo(output, _map_configGroupId_codec);
      if (OnlyGroupConfig != false) {
        output.WriteRawTag(24);
        output.WriteBool(OnlyGroupConfig);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += configKey_.CalculateSize(_repeated_configKey_codec);
      size += configGroupId_.CalculateSize(_map_configGroupId_codec);
      if (OnlyGroupConfig != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CGetSegmentationConfig other) {
      if (other == null) {
        return;
      }
      configKey_.Add(other.configKey_);
      configGroupId_.Add(other.configGroupId_);
      if (other.OnlyGroupConfig != false) {
        OnlyGroupConfig = other.OnlyGroupConfig;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            configKey_.AddEntriesFrom(input, _repeated_configKey_codec);
            break;
          }
          case 18: {
            configGroupId_.AddEntriesFrom(input, _map_configGroupId_codec);
            break;
          }
          case 24: {
            OnlyGroupConfig = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SGetSegmentationConfig : pb::IMessage<SGetSegmentationConfig> {
    private static readonly pb::MessageParser<SGetSegmentationConfig> _parser = new pb::MessageParser<SGetSegmentationConfig>(() => new SGetSegmentationConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SGetSegmentationConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DragonU3DSDK.Network.API.Protocol.RemoteConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetSegmentationConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetSegmentationConfig(SGetSegmentationConfig other) : this() {
      configData_ = other.configData_.Clone();
      groupIdData_ = other.groupIdData_.Clone();
      versionCode_ = other.versionCode_.Clone();
      campaignTypeCode_ = other.campaignTypeCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SGetSegmentationConfig Clone() {
      return new SGetSegmentationConfig(this);
    }

    /// <summary>Field number for the "config_data" field.</summary>
    public const int ConfigDataFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_configData_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 10);
    private readonly pbc::MapField<string, string> configData_ = new pbc::MapField<string, string>();
    /// <summary>
    /// 配置数据map, key为所传config_key, 对应value为功能配置的JSON字符串
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> ConfigData {
      get { return configData_; }
    }

    /// <summary>Field number for the "group_id_data" field.</summary>
    public const int GroupIdDataFieldNumber = 2;
    private static readonly pbc::MapField<string, uint>.Codec _map_groupIdData_codec
        = new pbc::MapField<string, uint>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForUInt32(16), 18);
    private readonly pbc::MapField<string, uint> groupIdData_ = new pbc::MapField<string, uint>();
    /// <summary>
    /// 分组ID数据map, key为所传config_key, 对应value为筛选后的分组ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, uint> GroupIdData {
      get { return groupIdData_; }
    }

    /// <summary>Field number for the "version_code" field.</summary>
    public const int VersionCodeFieldNumber = 3;
    private static readonly pbc::MapField<string, global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode>.Codec _map_versionCode_codec
        = new pbc::MapField<string, global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode.Parser), 26);
    private readonly pbc::MapField<string, global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode> versionCode_ = new pbc::MapField<string, global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode>();
    /// <summary>
    /// 配置数据map, key为所传config_key, 对应value为配置版本号信息（最小支持版本）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::DragonU3DSDK.Network.API.Protocol.ConfigVersionCode> VersionCode {
      get { return versionCode_; }
    }

    /// <summary>Field number for the "campaign_type_code" field.</summary>
    public const int CampaignTypeCodeFieldNumber = 4;
    private int campaignTypeCode_;
    /// <summary>
    /// 市场source_campaign的渠道名称映射类型数值。使用玩家的source_campaign名称，再根据后台Campaign配置，获取映射type code值（若无source_campaign信息，则为-1）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CampaignTypeCode {
      get { return campaignTypeCode_; }
      set {
        campaignTypeCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SGetSegmentationConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SGetSegmentationConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!ConfigData.Equals(other.ConfigData)) return false;
      if (!GroupIdData.Equals(other.GroupIdData)) return false;
      if (!VersionCode.Equals(other.VersionCode)) return false;
      if (CampaignTypeCode != other.CampaignTypeCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= ConfigData.GetHashCode();
      hash ^= GroupIdData.GetHashCode();
      hash ^= VersionCode.GetHashCode();
      if (CampaignTypeCode != 0) hash ^= CampaignTypeCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
#if UNITY_EDITOR
      return pb::JsonFormatter.ToDiagnosticString(this);
#else
return "pb::JsonFormatter.ToDiagnosticString not supported on Native Platform";
#endif
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      configData_.WriteTo(output, _map_configData_codec);
      groupIdData_.WriteTo(output, _map_groupIdData_codec);
      versionCode_.WriteTo(output, _map_versionCode_codec);
      if (CampaignTypeCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CampaignTypeCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += configData_.CalculateSize(_map_configData_codec);
      size += groupIdData_.CalculateSize(_map_groupIdData_codec);
      size += versionCode_.CalculateSize(_map_versionCode_codec);
      if (CampaignTypeCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CampaignTypeCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SGetSegmentationConfig other) {
      if (other == null) {
        return;
      }
      configData_.Add(other.configData_);
      groupIdData_.Add(other.groupIdData_);
      versionCode_.Add(other.versionCode_);
      if (other.CampaignTypeCode != 0) {
        CampaignTypeCode = other.CampaignTypeCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            configData_.AddEntriesFrom(input, _map_configData_codec);
            break;
          }
          case 18: {
            groupIdData_.AddEntriesFrom(input, _map_groupIdData_codec);
            break;
          }
          case 26: {
            versionCode_.AddEntriesFrom(input, _map_versionCode_codec);
            break;
          }
          case 32: {
            CampaignTypeCode = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
